In [184]:
import numpy as np
import pandas as pd

In [185]:
df=pd.read_csv('Processed Data.csv')
df

,spatial__geohash,StandardScaler__Temperature,remainder__timestamp,remainder__RoadType,remainder__NumberofLanes,remainder__LargeVehicles,demand
0,0.040506,0.495999,0.0,1,1,1,0.048804
1,0.205756,0.728631,0.0,1,3,0,0.118507
2,0.126582,0.646568,0.0,1,1,1,0.027132
3,0.013474,0.495999,0.0,1,1,1,0.003272
4,0.030915,0.407346,0.0,1,1,1,0.010819
...,...,...,...,...,...,...,...
77294,0.025254,0.418392,2.0,1,1,1,0.067203
77295,0.138003,0.469251,2.0,1,3,0,0.022859
77296,0.114036,0.547806,2.0,1,3,0,0.141342
77297,0.076453,0.593624,2.0,1,1,1,0.087574
77298,0.021961,0.257288,2.0,1,3,0,0.002944

In [186]:
x=df.drop('demand',axis=1)
y=df['demand']

In [187]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [188]:
from catboost import CatBoostRegressor
model=CatBoostRegressor()
model.fit(x_train,y_train)

Learning rate set to 0.07856
0:	learn: 0.1325478	total: 3.45ms	remaining: 3.44s
1:	learn: 0.1238412	total: 6.4ms	remaining: 3.19s
2:	learn: 0.1160492	total: 8.7ms	remaining: 2.89s
3:	learn: 0.1089365	total: 11.1ms	remaining: 2.75s
4:	learn: 0.1023450	total: 13.2ms	remaining: 2.63s
5:	learn: 0.0964772	total: 15.4ms	remaining: 2.54s
6:	learn: 0.0910278	total: 17.3ms	remaining: 2.46s
7:	learn: 0.0860042	total: 20.2ms	remaining: 2.51s
8:	learn: 0.0816576	total: 22.2ms	remaining: 2.44s
9:	learn: 0.0775328	total: 24.1ms	remaining: 2.38s
10:	learn: 0.0738511	total: 26.2ms	remaining: 2.35s
11:	learn: 0.0706106	total: 28.1ms	remaining: 2.31s
12:	learn: 0.0676496	total: 30ms	remaining: 2.28s
13:	learn: 0.0650599	total: 32ms	remaining: 2.25s
14:	learn: 0.0627770	total: 34.2ms	remaining: 2.24s
15:	learn: 0.0607407	total: 36ms	remaining: 2.21s
16:	learn: 0.0588264	total: 37.9ms	remaining: 2.19s
17:	learn: 0.0571498	total: 39.7ms	remaining: 2.16s
18:	learn: 0.0556926	total: 41.7ms	remaining: 2.15s
19:	learn: 0.0543782	total: 43.6ms	remaining: 2.14s
20:	learn: 0.0531831	total: 45.5ms	remaining: 2.12s
21:	learn: 0.0521088	total: 47.3ms	remaining: 2.1s
22:	learn: 0.0512375	total: 49.4ms	remaining: 2.1s
23:	learn: 0.0503681	total: 51.4ms	remaining: 2.09s
24:	learn: 0.0496630	total: 53.1ms	remaining: 2.07s
25:	learn: 0.0489470	total: 55ms	remaining: 2.06s
26:	learn: 0.0483440	total: 56.7ms	remaining: 2.04s
27:	learn: 0.0478428	total: 58.7ms	remaining: 2.04s
28:	learn: 0.0473280	total: 60.6ms	remaining: 2.03s
29:	learn: 0.0468639	total: 62.5ms	remaining: 2.02s
30:	learn: 0.0464035	total: 64.3ms	remaining: 2.01s
31:	learn: 0.0460453	total: 66.4ms	remaining: 2.01s
32:	learn: 0.0457289	total: 68.2ms	remaining: 2s
33:	learn: 0.0453885	total: 70.3ms	remaining: 2s
34:	learn: 0.0451256	total: 72.3ms	remaining: 1.99s
35:	learn: 0.0449050	total: 74.4ms	remaining: 1.99s
36:	learn: 0.0446800	total: 76.8ms	remaining: 2s
37:	learn: 0.0444962	total: 78.8ms	remaining: 1.99s
38:	learn: 0.0443000	total: 80.7ms	remaining: 1.99s
39:	learn: 0.0441553	total: 82.7ms	remaining: 1.99s
40:	learn: 0.0439788	total: 84.9ms	remaining: 1.99s
41:	learn: 0.0438598	total: 87.1ms	remaining: 1.99s
42:	learn: 0.0437358	total: 89.3ms	remaining: 1.99s
43:	learn: 0.0436209	total: 91.5ms	remaining: 1.99s
44:	learn: 0.0435240	total: 93.9ms	remaining: 1.99s
45:	learn: 0.0434210	total: 95.9ms	remaining: 1.99s
46:	learn: 0.0433259	total: 97.8ms	remaining: 1.98s
47:	learn: 0.0432357	total: 99.7ms	remaining: 1.98s
48:	learn: 0.0431445	total: 102ms	remaining: 1.97s
49:	learn: 0.0430841	total: 104ms	remaining: 1.97s
50:	learn: 0.0430104	total: 106ms	remaining: 1.97s
51:	learn: 0.0429333	total: 108ms	remaining: 1.96s
52:	learn: 0.0428705	total: 110ms	remaining: 1.96s
53:	learn: 0.0428246	total: 111ms	remaining: 1.95s
54:	learn: 0.0427558	total: 113ms	remaining: 1.95s
55:	learn: 0.0427091	total: 116ms	remaining: 1.95s
56:	learn: 0.0426604	total: 117ms	remaining: 1.94s
57:	learn: 0.0425876	total: 119ms	remaining: 1.94s
58:	learn: 0.0425194	total: 121ms	remaining: 1.94s
59:	learn: 0.0424862	total: 124ms	remaining: 1.94s
60:	learn: 0.0424536	total: 126ms	remaining: 1.93s
61:	learn: 0.0424240	total: 127ms	remaining: 1.93s
62:	learn: 0.0423796	total: 129ms	remaining: 1.92s
63:	learn: 0.0423388	total: 131ms	remaining: 1.92s
64:	learn: 0.0423033	total: 133ms	remaining: 1.92s
65:	learn: 0.0422574	total: 135ms	remaining: 1.91s
66:	learn: 0.0422225	total: 137ms	remaining: 1.91s
67:	learn: 0.0421901	total: 139ms	remaining: 1.91s
68:	learn: 0.0421645	total: 141ms	remaining: 1.9s
69:	learn: 0.0421345	total: 143ms	remaining: 1.9s
70:	learn: 0.0420872	total: 145ms	remaining: 1.89s
71:	learn: 0.0420612	total: 147ms	remaining: 1.89s
72:	learn: 0.0420467	total: 149ms	remaining: 1.89s
73:	learn: 0.0420282	total: 151ms	remaining: 1.89s
74:	learn: 0.0419963	total: 153ms	remaining: 1.88s
75:	learn: 0.0419610	total: 155ms	remaining: 1.88s
76:	learn: 0.0419292	total: 157ms	remaining: 1.88s
77:	learn: 0.0419026	total: 159ms	remaining: 1.87s
78:	learn: 0.0418876	total: 161ms	remaining: 1.87s
79:	learn: 0.0418674	total: 163ms	remaining: 1.87s
80:	learn: 0.0418424	total: 164ms	remaining: 1.87s
81:	learn: 0.0418175	total: 166ms	remaining: 1.86s
82:	learn: 0.0417887	total: 169ms	remaining: 1.86s
83:	learn: 0.0417565	total: 171ms	remaining: 1.86s
84:	learn: 0.0417050	total: 173ms	remaining: 1.86s
85:	learn: 0.0416928	total: 175ms	remaining: 1.86s
86:	learn: 0.0416659	total: 177ms	remaining: 1.85s
87:	learn: 0.0416451	total: 179ms	remaining: 1.85s
88:	learn: 0.0416320	total: 181ms	remaining: 1.85s
89:	learn: 0.0416135	total: 183ms	remaining: 1.85s
90:	learn: 0.0415937	total: 186ms	remaining: 1.85s
91:	learn: 0.0415775	total: 188ms	remaining: 1.85s
92:	learn: 0.0415684	total: 190ms	remaining: 1.85s
93:	learn: 0.0415492	total: 192ms	remaining: 1.85s
94:	learn: 0.0415116	total: 194ms	remaining: 1.85s
95:	learn: 0.0414900	total: 197ms	remaining: 1.85s
96:	learn: 0.0414493	total: 199ms	remaining: 1.85s
97:	learn: 0.0413907	total: 202ms	remaining: 1.86s
98:	learn: 0.0413754	total: 204ms	remaining: 1.86s
99:	learn: 0.0413311	total: 206ms	remaining: 1.86s
100:	learn: 0.0413197	total: 208ms	remaining: 1.85s
101:	learn: 0.0412887	total: 211ms	remaining: 1.85s
102:	learn: 0.0412666	total: 213ms	remaining: 1.85s
103:	learn: 0.0412117	total: 215ms	remaining: 1.85s
104:	learn: 0.0411970	total: 218ms	remaining: 1.85s
105:	learn: 0.0411800	total: 220ms	remaining: 1.86s
106:	learn: 0.0411576	total: 222ms	remaining: 1.86s
107:	learn: 0.0411494	total: 225ms	remaining: 1.86s
108:	learn: 0.0411327	total: 227ms	remaining: 1.86s
109:	learn: 0.0411189	total: 230ms	remaining: 1.86s
110:	learn: 0.0411079	total: 232ms	remaining: 1.86s
111:	learn: 0.0410908	total: 234ms	remaining: 1.86s
112:	learn: 0.0410527	total: 237ms	remaining: 1.86s
113:	learn: 0.0410434	total: 239ms	remaining: 1.86s
114:	learn: 0.0410221	total: 241ms	remaining: 1.85s
115:	learn: 0.0410153	total: 243ms	remaining: 1.85s
116:	learn: 0.0410131	total: 245ms	remaining: 1.85s
117:	learn: 0.0410002	total: 247ms	remaining: 1.85s
118:	learn: 0.0409825	total: 250ms	remaining: 1.85s
119:	learn: 0.0409453	total: 252ms	remaining: 1.85s
120:	learn: 0.0409356	total: 254ms	remaining: 1.85s
121:	learn: 0.0409211	total: 257ms	remaining: 1.85s
122:	learn: 0.0409047	total: 259ms	remaining: 1.84s
123:	learn: 0.0408743	total: 261ms	remaining: 1.84s
124:	learn: 0.0408359	total: 264ms	remaining: 1.84s
125:	learn: 0.0408061	total: 266ms	remaining: 1.85s
126:	learn: 0.0407918	total: 269ms	remaining: 1.84s
127:	learn: 0.0407663	total: 271ms	remaining: 1.84s
128:	learn: 0.0407485	total: 273ms	remaining: 1.84s
129:	learn: 0.0407324	total: 276ms	remaining: 1.84s
130:	learn: 0.0406914	total: 278ms	remaining: 1.85s
131:	learn: 0.0406812	total: 281ms	remaining: 1.85s
132:	learn: 0.0406693	total: 283ms	remaining: 1.85s
133:	learn: 0.0406591	total: 286ms	remaining: 1.85s
134:	learn: 0.0406346	total: 289ms	remaining: 1.85s
135:	learn: 0.0406184	total: 291ms	remaining: 1.85s
136:	learn: 0.0406071	total: 293ms	remaining: 1.85s
137:	learn: 0.0405730	total: 296ms	remaining: 1.85s
138:	learn: 0.0405638	total: 298ms	remaining: 1.85s
139:	learn: 0.0405450	total: 301ms	remaining: 1.85s
140:	learn: 0.0405236	total: 303ms	remaining: 1.85s
141:	learn: 0.0405119	total: 306ms	remaining: 1.85s
142:	learn: 0.0405024	total: 308ms	remaining: 1.84s
143:	learn: 0.0404813	total: 311ms	remaining: 1.85s
144:	learn: 0.0404432	total: 313ms	remaining: 1.85s
145:	learn: 0.0404280	total: 316ms	remaining: 1.85s
146:	learn: 0.0404065	total: 318ms	remaining: 1.85s
147:	learn: 0.0403729	total: 321ms	remaining: 1.85s
148:	learn: 0.0403625	total: 323ms	remaining: 1.84s
149:	learn: 0.0403292	total: 326ms	remaining: 1.84s
150:	learn: 0.0403123	total: 328ms	remaining: 1.85s
151:	learn: 0.0402932	total: 331ms	remaining: 1.84s
152:	learn: 0.0402823	total: 333ms	remaining: 1.84s
153:	learn: 0.0402699	total: 336ms	remaining: 1.84s
154:	learn: 0.0402453	total: 338ms	remaining: 1.84s
155:	learn: 0.0402306	total: 340ms	remaining: 1.84s
156:	learn: 0.0402137	total: 343ms	remaining: 1.84s
157:	learn: 0.0401875	total: 345ms	remaining: 1.84s
158:	learn: 0.0401739	total: 348ms	remaining: 1.84s
159:	learn: 0.0401615	total: 350ms	remaining: 1.84s
160:	learn: 0.0401465	total: 353ms	remaining: 1.84s
161:	learn: 0.0401342	total: 355ms	remaining: 1.84s
162:	learn: 0.0401229	total: 358ms	remaining: 1.84s
163:	learn: 0.0401035	total: 360ms	remaining: 1.84s
164:	learn: 0.0400951	total: 363ms	remaining: 1.84s
165:	learn: 0.0400851	total: 367ms	remaining: 1.84s
166:	learn: 0.0400723	total: 370ms	remaining: 1.84s
167:	learn: 0.0400534	total: 372ms	remaining: 1.84s
168:	learn: 0.0400439	total: 375ms	remaining: 1.84s
169:	learn: 0.0400341	total: 378ms	remaining: 1.85s
170:	learn: 0.0400246	total: 381ms	remaining: 1.85s
171:	learn: 0.0400165	total: 385ms	remaining: 1.85s
172:	learn: 0.0400094	total: 388ms	remaining: 1.85s
173:	learn: 0.0399974	total: 391ms	remaining: 1.85s
174:	learn: 0.0399836	total: 394ms	remaining: 1.86s
175:	learn: 0.0399757	total: 397ms	remaining: 1.86s
176:	learn: 0.0399638	total: 400ms	remaining: 1.86s
177:	learn: 0.0399465	total: 403ms	remaining: 1.86s
178:	learn: 0.0399381	total: 406ms	remaining: 1.86s
179:	learn: 0.0399307	total: 408ms	remaining: 1.86s
180:	learn: 0.0399230	total: 411ms	remaining: 1.86s
181:	learn: 0.0399071	total: 414ms	remaining: 1.86s
182:	learn: 0.0399016	total: 417ms	remaining: 1.86s
183:	learn: 0.0398954	total: 420ms	remaining: 1.86s
184:	learn: 0.0398839	total: 423ms	remaining: 1.86s
185:	learn: 0.0398740	total: 426ms	remaining: 1.86s
186:	learn: 0.0398576	total: 428ms	remaining: 1.86s
187:	learn: 0.0398452	total: 431ms	remaining: 1.86s
188:	learn: 0.0398353	total: 434ms	remaining: 1.86s
189:	learn: 0.0398199	total: 437ms	remaining: 1.86s
190:	learn: 0.0398132	total: 440ms	remaining: 1.86s
191:	learn: 0.0398014	total: 442ms	remaining: 1.86s
192:	learn: 0.0397787	total: 445ms	remaining: 1.86s
193:	learn: 0.0397678	total: 448ms	remaining: 1.86s
194:	learn: 0.0397588	total: 450ms	remaining: 1.86s
195:	learn: 0.0397390	total: 453ms	remaining: 1.86s
196:	learn: 0.0397316	total: 455ms	remaining: 1.86s
197:	learn: 0.0397128	total: 458ms	remaining: 1.85s
198:	learn: 0.0397057	total: 460ms	remaining: 1.85s
199:	learn: 0.0396953	total: 463ms	remaining: 1.85s
200:	learn: 0.0396757	total: 466ms	remaining: 1.85s
201:	learn: 0.0396651	total: 468ms	remaining: 1.85s
202:	learn: 0.0396567	total: 471ms	remaining: 1.85s
203:	learn: 0.0396495	total: 473ms	remaining: 1.85s
204:	learn: 0.0396374	total: 476ms	remaining: 1.84s
205:	learn: 0.0396215	total: 479ms	remaining: 1.84s
206:	learn: 0.0396154	total: 481ms	remaining: 1.84s
207:	learn: 0.0396071	total: 484ms	remaining: 1.84s
208:	learn: 0.0395961	total: 486ms	remaining: 1.84s
209:	learn: 0.0395796	total: 488ms	remaining: 1.84s
210:	learn: 0.0395692	total: 491ms	remaining: 1.83s
211:	learn: 0.0395549	total: 493ms	remaining: 1.83s
212:	learn: 0.0395457	total: 496ms	remaining: 1.83s
213:	learn: 0.0395356	total: 498ms	remaining: 1.83s
214:	learn: 0.0395296	total: 500ms	remaining: 1.83s
215:	learn: 0.0395213	total: 503ms	remaining: 1.83s
216:	learn: 0.0395020	total: 506ms	remaining: 1.82s
217:	learn: 0.0394958	total: 508ms	remaining: 1.82s
218:	learn: 0.0394795	total: 511ms	remaining: 1.82s
219:	learn: 0.0394652	total: 514ms	remaining: 1.82s
220:	learn: 0.0394562	total: 516ms	remaining: 1.82s
221:	learn: 0.0394455	total: 519ms	remaining: 1.82s
222:	learn: 0.0394382	total: 521ms	remaining: 1.81s
223:	learn: 0.0394310	total: 523ms	remaining: 1.81s
224:	learn: 0.0394245	total: 526ms	remaining: 1.81s
225:	learn: 0.0394180	total: 529ms	remaining: 1.81s
226:	learn: 0.0394096	total: 531ms	remaining: 1.81s
227:	learn: 0.0394035	total: 533ms	remaining: 1.81s
228:	learn: 0.0393781	total: 536ms	remaining: 1.8s
229:	learn: 0.0393675	total: 539ms	remaining: 1.8s
230:	learn: 0.0393614	total: 541ms	remaining: 1.8s
231:	learn: 0.0393483	total: 543ms	remaining: 1.8s
232:	learn: 0.0393264	total: 546ms	remaining: 1.8s
233:	learn: 0.0393209	total: 548ms	remaining: 1.79s
234:	learn: 0.0393116	total: 551ms	remaining: 1.79s
235:	learn: 0.0393056	total: 553ms	remaining: 1.79s
236:	learn: 0.0393004	total: 556ms	remaining: 1.79s
237:	learn: 0.0392927	total: 558ms	remaining: 1.79s
238:	learn: 0.0392685	total: 561ms	remaining: 1.79s
239:	learn: 0.0392627	total: 563ms	remaining: 1.78s
240:	learn: 0.0392574	total: 566ms	remaining: 1.78s
241:	learn: 0.0392439	total: 568ms	remaining: 1.78s
242:	learn: 0.0392336	total: 571ms	remaining: 1.78s
243:	learn: 0.0392190	total: 573ms	remaining: 1.77s
244:	learn: 0.0392056	total: 575ms	remaining: 1.77s
245:	learn: 0.0392008	total: 578ms	remaining: 1.77s
246:	learn: 0.0391968	total: 580ms	remaining: 1.77s
247:	learn: 0.0391893	total: 582ms	remaining: 1.76s
248:	learn: 0.0391854	total: 584ms	remaining: 1.76s
249:	learn: 0.0391773	total: 586ms	remaining: 1.76s
250:	learn: 0.0391599	total: 589ms	remaining: 1.76s
251:	learn: 0.0391519	total: 591ms	remaining: 1.75s
252:	learn: 0.0391430	total: 594ms	remaining: 1.75s
253:	learn: 0.0391344	total: 596ms	remaining: 1.75s
254:	learn: 0.0391147	total: 598ms	remaining: 1.75s
255:	learn: 0.0391059	total: 600ms	remaining: 1.75s
256:	learn: 0.0390981	total: 603ms	remaining: 1.74s
257:	learn: 0.0390796	total: 605ms	remaining: 1.74s
258:	learn: 0.0390753	total: 607ms	remaining: 1.74s
259:	learn: 0.0390695	total: 610ms	remaining: 1.74s
260:	learn: 0.0390638	total: 612ms	remaining: 1.73s
261:	learn: 0.0390573	total: 614ms	remaining: 1.73s
262:	learn: 0.0390492	total: 616ms	remaining: 1.73s
263:	learn: 0.0390431	total: 619ms	remaining: 1.73s
264:	learn: 0.0390391	total: 621ms	remaining: 1.72s
265:	learn: 0.0390338	total: 623ms	remaining: 1.72s
266:	learn: 0.0390142	total: 626ms	remaining: 1.72s
267:	learn: 0.0390038	total: 628ms	remaining: 1.72s
268:	learn: 0.0389888	total: 630ms	remaining: 1.71s
269:	learn: 0.0389830	total: 633ms	remaining: 1.71s
270:	learn: 0.0389785	total: 635ms	remaining: 1.71s
271:	learn: 0.0389618	total: 638ms	remaining: 1.71s
272:	learn: 0.0389528	total: 640ms	remaining: 1.7s
273:	learn: 0.0389380	total: 643ms	remaining: 1.7s
274:	learn: 0.0389307	total: 645ms	remaining: 1.7s
275:	learn: 0.0389243	total: 647ms	remaining: 1.7s
276:	learn: 0.0389160	total: 650ms	remaining: 1.7s
277:	learn: 0.0389102	total: 653ms	remaining: 1.69s
278:	learn: 0.0389024	total: 655ms	remaining: 1.69s
279:	learn: 0.0388960	total: 657ms	remaining: 1.69s
280:	learn: 0.0388892	total: 659ms	remaining: 1.69s
281:	learn: 0.0388840	total: 661ms	remaining: 1.68s
282:	learn: 0.0388787	total: 663ms	remaining: 1.68s
283:	learn: 0.0388671	total: 666ms	remaining: 1.68s
284:	learn: 0.0388615	total: 668ms	remaining: 1.68s
285:	learn: 0.0388489	total: 670ms	remaining: 1.67s
286:	learn: 0.0388391	total: 672ms	remaining: 1.67s
287:	learn: 0.0388250	total: 674ms	remaining: 1.67s
288:	learn: 0.0388164	total: 677ms	remaining: 1.66s
289:	learn: 0.0388122	total: 679ms	remaining: 1.66s
290:	learn: 0.0388015	total: 681ms	remaining: 1.66s
291:	learn: 0.0387978	total: 684ms	remaining: 1.66s
292:	learn: 0.0387883	total: 686ms	remaining: 1.66s
293:	learn: 0.0387796	total: 688ms	remaining: 1.65s
294:	learn: 0.0387722	total: 691ms	remaining: 1.65s
295:	learn: 0.0387609	total: 693ms	remaining: 1.65s
296:	learn: 0.0387569	total: 695ms	remaining: 1.65s
297:	learn: 0.0387519	total: 698ms	remaining: 1.64s
298:	learn: 0.0387469	total: 700ms	remaining: 1.64s
299:	learn: 0.0387426	total: 703ms	remaining: 1.64s
300:	learn: 0.0387365	total: 705ms	remaining: 1.64s
301:	learn: 0.0387259	total: 708ms	remaining: 1.64s
302:	learn: 0.0387224	total: 710ms	remaining: 1.63s
303:	learn: 0.0387123	total: 713ms	remaining: 1.63s
304:	learn: 0.0387042	total: 716ms	remaining: 1.63s
305:	learn: 0.0387011	total: 718ms	remaining: 1.63s
306:	learn: 0.0386924	total: 721ms	remaining: 1.63s
307:	learn: 0.0386838	total: 723ms	remaining: 1.63s
308:	learn: 0.0386792	total: 726ms	remaining: 1.62s
309:	learn: 0.0386675	total: 728ms	remaining: 1.62s
310:	learn: 0.0386620	total: 731ms	remaining: 1.62s
311:	learn: 0.0386586	total: 733ms	remaining: 1.62s
312:	learn: 0.0386517	total: 735ms	remaining: 1.61s
313:	learn: 0.0386412	total: 738ms	remaining: 1.61s
314:	learn: 0.0386359	total: 741ms	remaining: 1.61s
315:	learn: 0.0386259	total: 743ms	remaining: 1.61s
316:	learn: 0.0386195	total: 746ms	remaining: 1.61s
317:	learn: 0.0386154	total: 749ms	remaining: 1.6s
318:	learn: 0.0386099	total: 751ms	remaining: 1.6s
319:	learn: 0.0386053	total: 753ms	remaining: 1.6s
320:	learn: 0.0385945	total: 756ms	remaining: 1.6s
321:	learn: 0.0385843	total: 759ms	remaining: 1.6s
322:	learn: 0.0385740	total: 761ms	remaining: 1.59s
323:	learn: 0.0385700	total: 764ms	remaining: 1.59s
324:	learn: 0.0385637	total: 766ms	remaining: 1.59s
325:	learn: 0.0385580	total: 769ms	remaining: 1.59s
326:	learn: 0.0385464	total: 771ms	remaining: 1.59s
327:	learn: 0.0385412	total: 774ms	remaining: 1.58s
328:	learn: 0.0385349	total: 776ms	remaining: 1.58s
329:	learn: 0.0385322	total: 779ms	remaining: 1.58s
330:	learn: 0.0385222	total: 782ms	remaining: 1.58s
331:	learn: 0.0385133	total: 785ms	remaining: 1.58s
332:	learn: 0.0385016	total: 787ms	remaining: 1.58s
333:	learn: 0.0384958	total: 790ms	remaining: 1.57s
334:	learn: 0.0384911	total: 793ms	remaining: 1.57s
335:	learn: 0.0384772	total: 795ms	remaining: 1.57s
336:	learn: 0.0384695	total: 798ms	remaining: 1.57s
337:	learn: 0.0384610	total: 800ms	remaining: 1.57s
338:	learn: 0.0384552	total: 802ms	remaining: 1.56s
339:	learn: 0.0384508	total: 805ms	remaining: 1.56s
340:	learn: 0.0384429	total: 807ms	remaining: 1.56s
341:	learn: 0.0384356	total: 810ms	remaining: 1.56s
342:	learn: 0.0384257	total: 813ms	remaining: 1.56s
343:	learn: 0.0384221	total: 816ms	remaining: 1.56s
344:	learn: 0.0384119	total: 819ms	remaining: 1.55s
345:	learn: 0.0384077	total: 822ms	remaining: 1.55s
346:	learn: 0.0384004	total: 825ms	remaining: 1.55s
347:	learn: 0.0383918	total: 828ms	remaining: 1.55s
348:	learn: 0.0383840	total: 830ms	remaining: 1.55s
349:	learn: 0.0383798	total: 833ms	remaining: 1.55s
350:	learn: 0.0383728	total: 836ms	remaining: 1.54s
351:	learn: 0.0383648	total: 839ms	remaining: 1.54s
352:	learn: 0.0383604	total: 842ms	remaining: 1.54s
353:	learn: 0.0383511	total: 845ms	remaining: 1.54s
354:	learn: 0.0383400	total: 848ms	remaining: 1.54s
355:	learn: 0.0383360	total: 850ms	remaining: 1.54s
356:	learn: 0.0383258	total: 853ms	remaining: 1.54s
357:	learn: 0.0383194	total: 856ms	remaining: 1.53s
358:	learn: 0.0383087	total: 858ms	remaining: 1.53s
359:	learn: 0.0383049	total: 861ms	remaining: 1.53s
360:	learn: 0.0382997	total: 864ms	remaining: 1.53s
361:	learn: 0.0382849	total: 867ms	remaining: 1.53s
362:	learn: 0.0382717	total: 869ms	remaining: 1.52s
363:	learn: 0.0382658	total: 872ms	remaining: 1.52s
364:	learn: 0.0382504	total: 875ms	remaining: 1.52s
365:	learn: 0.0382436	total: 877ms	remaining: 1.52s
366:	learn: 0.0382400	total: 881ms	remaining: 1.52s
367:	learn: 0.0382325	total: 884ms	remaining: 1.52s
368:	learn: 0.0382222	total: 887ms	remaining: 1.52s
369:	learn: 0.0382184	total: 889ms	remaining: 1.51s
370:	learn: 0.0382139	total: 892ms	remaining: 1.51s
371:	learn: 0.0382093	total: 895ms	remaining: 1.51s
372:	learn: 0.0382018	total: 898ms	remaining: 1.51s
373:	learn: 0.0381950	total: 900ms	remaining: 1.51s
374:	learn: 0.0381916	total: 903ms	remaining: 1.5s
375:	learn: 0.0381872	total: 906ms	remaining: 1.5s
376:	learn: 0.0381797	total: 909ms	remaining: 1.5s
377:	learn: 0.0381728	total: 912ms	remaining: 1.5s
378:	learn: 0.0381696	total: 915ms	remaining: 1.5s
379:	learn: 0.0381648	total: 918ms	remaining: 1.5s
380:	learn: 0.0381611	total: 921ms	remaining: 1.5s
381:	learn: 0.0381529	total: 923ms	remaining: 1.49s
382:	learn: 0.0381497	total: 926ms	remaining: 1.49s
383:	learn: 0.0381457	total: 929ms	remaining: 1.49s
384:	learn: 0.0381378	total: 932ms	remaining: 1.49s
385:	learn: 0.0381291	total: 934ms	remaining: 1.49s

In [189]:
y_pred=model.predict(x_test)
y_pred

array([0.06644288, 0.08221176, 0.03465498, ..., 0.03312071, 0.02493894,
       0.01323976])

In [190]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9125597477308279

In [196]:
model_submit=voting_model.fit(x,y)

0:	learn: 0.1409759	total: 3.3ms	remaining: 4.95s
1:	learn: 0.1397701	total: 10.1ms	remaining: 7.57s
2:	learn: 0.1385650	total: 13.9ms	remaining: 6.95s
3:	learn: 0.1373732	total: 16.5ms	remaining: 6.18s
4:	learn: 0.1361899	total: 20.6ms	remaining: 6.15s
5:	learn: 0.1350521	total: 23.3ms	remaining: 5.8s
6:	learn: 0.1339335	total: 28.1ms	remaining: 6s
7:	learn: 0.1327981	total: 31.2ms	remaining: 5.81s
8:	learn: 0.1316590	total: 36.3ms	remaining: 6.01s
9:	learn: 0.1305311	total: 40.9ms	remaining: 6.1s
10:	learn: 0.1294160	total: 45.7ms	remaining: 6.19s
11:	learn: 0.1283052	total: 50.2ms	remaining: 6.23s
12:	learn: 0.1272368	total: 53.4ms	remaining: 6.11s
13:	learn: 0.1261489	total: 57.9ms	remaining: 6.15s
14:	learn: 0.1250970	total: 62.8ms	remaining: 6.21s
15:	learn: 0.1240427	total: 67.3ms	remaining: 6.24s
16:	learn: 0.1230389	total: 69.3ms	remaining: 6.04s
17:	learn: 0.1220164	total: 73.9ms	remaining: 6.09s
18:	learn: 0.1209907	total: 78.8ms	remaining: 6.14s
19:	learn: 0.1199800	total: 84ms	remaining: 6.21s
20:	learn: 0.1189786	total: 89.6ms	remaining: 6.31s
21:	learn: 0.1180335	total: 91.7ms	remaining: 6.16s
22:	learn: 0.1170601	total: 96.2ms	remaining: 6.18s
23:	learn: 0.1160965	total: 101ms	remaining: 6.2s
24:	learn: 0.1151812	total: 103ms	remaining: 6.07s
25:	learn: 0.1142403	total: 106ms	remaining: 6.03s
26:	learn: 0.1133137	total: 109ms	remaining: 5.97s
27:	learn: 0.1123994	total: 114ms	remaining: 5.99s
28:	learn: 0.1115292	total: 116ms	remaining: 5.88s
29:	learn: 0.1106474	total: 121ms	remaining: 5.92s
30:	learn: 0.1097678	total: 125ms	remaining: 5.94s
31:	learn: 0.1088864	total: 130ms	remaining: 5.97s
32:	learn: 0.1080066	total: 135ms	remaining: 5.99s
33:	learn: 0.1071560	total: 138ms	remaining: 5.93s
34:	learn: 0.1063075	total: 142ms	remaining: 5.95s
35:	learn: 0.1054678	total: 147ms	remaining: 5.96s
36:	learn: 0.1046332	total: 151ms	remaining: 5.98s
37:	learn: 0.1038505	total: 153ms	remaining: 5.89s
38:	learn: 0.1030333	total: 158ms	remaining: 5.91s
39:	learn: 0.1022363	total: 162ms	remaining: 5.92s
40:	learn: 0.1014441	total: 167ms	remaining: 5.93s
41:	learn: 0.1006681	total: 169ms	remaining: 5.88s
42:	learn: 0.0999118	total: 174ms	remaining: 5.9s
43:	learn: 0.0991312	total: 179ms	remaining: 5.92s
44:	learn: 0.0983743	total: 183ms	remaining: 5.92s
45:	learn: 0.0976204	total: 188ms	remaining: 5.93s
46:	learn: 0.0968935	total: 191ms	remaining: 5.91s
47:	learn: 0.0961685	total: 196ms	remaining: 5.92s
48:	learn: 0.0954388	total: 200ms	remaining: 5.92s
49:	learn: 0.0947363	total: 205ms	remaining: 5.94s
50:	learn: 0.0940286	total: 210ms	remaining: 5.96s
51:	learn: 0.0933180	total: 214ms	remaining: 5.97s
52:	learn: 0.0926320	total: 219ms	remaining: 5.98s
53:	learn: 0.0919474	total: 224ms	remaining: 5.99s
54:	learn: 0.0912894	total: 228ms	remaining: 6s
55:	learn: 0.0906257	total: 233ms	remaining: 6.02s
56:	learn: 0.0899861	total: 237ms	remaining: 5.99s
57:	learn: 0.0893440	total: 241ms	remaining: 6s
58:	learn: 0.0887108	total: 244ms	remaining: 5.96s
59:	learn: 0.0880739	total: 248ms	remaining: 5.96s
60:	learn: 0.0874453	total: 253ms	remaining: 5.97s
61:	learn: 0.0868258	total: 258ms	remaining: 5.97s
62:	learn: 0.0862161	total: 262ms	remaining: 5.97s
63:	learn: 0.0855987	total: 267ms	remaining: 5.98s
64:	learn: 0.0850026	total: 272ms	remaining: 5.99s
65:	learn: 0.0844129	total: 276ms	remaining: 6s
66:	learn: 0.0838373	total: 280ms	remaining: 6s
67:	learn: 0.0832504	total: 285ms	remaining: 6s
68:	learn: 0.0826919	total: 288ms	remaining: 5.97s
69:	learn: 0.0821335	total: 291ms	remaining: 5.95s
70:	learn: 0.0816029	total: 294ms	remaining: 5.91s
71:	learn: 0.0810462	total: 298ms	remaining: 5.91s
72:	learn: 0.0805124	total: 302ms	remaining: 5.91s
73:	learn: 0.0799952	total: 307ms	remaining: 5.92s
74:	learn: 0.0794910	total: 309ms	remaining: 5.88s
75:	learn: 0.0789763	total: 314ms	remaining: 5.88s
76:	learn: 0.0784566	total: 319ms	remaining: 5.89s
77:	learn: 0.0779570	total: 323ms	remaining: 5.89s
78:	learn: 0.0774554	total: 328ms	remaining: 5.89s
79:	learn: 0.0769506	total: 332ms	remaining: 5.89s
80:	learn: 0.0764627	total: 335ms	remaining: 5.88s
81:	learn: 0.0759810	total: 340ms	remaining: 5.88s
82:	learn: 0.0754966	total: 344ms	remaining: 5.88s
83:	learn: 0.0750151	total: 349ms	remaining: 5.88s
84:	learn: 0.0745633	total: 353ms	remaining: 5.88s
85:	learn: 0.0740989	total: 358ms	remaining: 5.88s
86:	learn: 0.0736480	total: 362ms	remaining: 5.89s
87:	learn: 0.0732052	total: 367ms	remaining: 5.89s
88:	learn: 0.0727644	total: 372ms	remaining: 5.89s
89:	learn: 0.0723172	total: 377ms	remaining: 5.9s
90:	learn: 0.0718768	total: 382ms	remaining: 5.91s
91:	learn: 0.0714429	total: 387ms	remaining: 5.92s
92:	learn: 0.0710235	total: 391ms	remaining: 5.92s
93:	learn: 0.0705973	total: 396ms	remaining: 5.92s
94:	learn: 0.0701834	total: 401ms	remaining: 5.93s
95:	learn: 0.0697768	total: 406ms	remaining: 5.93s
96:	learn: 0.0693882	total: 411ms	remaining: 5.94s
97:	learn: 0.0689872	total: 416ms	remaining: 5.95s
98:	learn: 0.0685970	total: 420ms	remaining: 5.95s
99:	learn: 0.0682078	total: 425ms	remaining: 5.95s
100:	learn: 0.0678307	total: 430ms	remaining: 5.95s
101:	learn: 0.0674515	total: 434ms	remaining: 5.95s
102:	learn: 0.0670788	total: 439ms	remaining: 5.96s
103:	learn: 0.0667164	total: 444ms	remaining: 5.96s
104:	learn: 0.0663463	total: 449ms	remaining: 5.96s
105:	learn: 0.0659896	total: 453ms	remaining: 5.96s
106:	learn: 0.0656327	total: 458ms	remaining: 5.96s
107:	learn: 0.0652850	total: 461ms	remaining: 5.94s
108:	learn: 0.0649348	total: 466ms	remaining: 5.94s
109:	learn: 0.0645881	total: 470ms	remaining: 5.94s
110:	learn: 0.0642555	total: 475ms	remaining: 5.94s
111:	learn: 0.0639192	total: 479ms	remaining: 5.94s
112:	learn: 0.0635925	total: 484ms	remaining: 5.94s
113:	learn: 0.0632793	total: 488ms	remaining: 5.94s
114:	learn: 0.0629678	total: 492ms	remaining: 5.92s
115:	learn: 0.0626602	total: 496ms	remaining: 5.92s
116:	learn: 0.0623542	total: 501ms	remaining: 5.92s
117:	learn: 0.0620525	total: 505ms	remaining: 5.92s
118:	learn: 0.0617588	total: 510ms	remaining: 5.92s
119:	learn: 0.0614738	total: 515ms	remaining: 5.92s
120:	learn: 0.0611822	total: 519ms	remaining: 5.91s
121:	learn: 0.0609044	total: 524ms	remaining: 5.91s
122:	learn: 0.0606140	total: 528ms	remaining: 5.91s
123:	learn: 0.0603343	total: 533ms	remaining: 5.91s
124:	learn: 0.0600537	total: 537ms	remaining: 5.91s
125:	learn: 0.0597924	total: 542ms	remaining: 5.91s
126:	learn: 0.0595378	total: 546ms	remaining: 5.9s
127:	learn: 0.0592613	total: 551ms	remaining: 5.9s
128:	learn: 0.0589924	total: 555ms	remaining: 5.9s
129:	learn: 0.0587401	total: 559ms	remaining: 5.9s
130:	learn: 0.0584797	total: 564ms	remaining: 5.9s
131:	learn: 0.0582294	total: 569ms	remaining: 5.89s
132:	learn: 0.0579727	total: 573ms	remaining: 5.89s
133:	learn: 0.0577263	total: 578ms	remaining: 5.89s
134:	learn: 0.0574888	total: 582ms	remaining: 5.89s
135:	learn: 0.0572505	total: 587ms	remaining: 5.88s
136:	learn: 0.0570160	total: 591ms	remaining: 5.88s
137:	learn: 0.0567876	total: 595ms	remaining: 5.88s
138:	learn: 0.0565691	total: 599ms	remaining: 5.86s
139:	learn: 0.0563382	total: 604ms	remaining: 5.86s
140:	learn: 0.0561348	total: 606ms	remaining: 5.84s
141:	learn: 0.0559162	total: 611ms	remaining: 5.84s
142:	learn: 0.0557017	total: 615ms	remaining: 5.84s
143:	learn: 0.0554834	total: 620ms	remaining: 5.84s
144:	learn: 0.0552701	total: 624ms	remaining: 5.83s
145:	learn: 0.0550686	total: 629ms	remaining: 5.83s
146:	learn: 0.0548669	total: 634ms	remaining: 5.83s
147:	learn: 0.0546729	total: 638ms	remaining: 5.83s
148:	learn: 0.0544825	total: 643ms	remaining: 5.83s
149:	learn: 0.0542915	total: 647ms	remaining: 5.82s
150:	learn: 0.0540965	total: 652ms	remaining: 5.82s
151:	learn: 0.0539007	total: 656ms	remaining: 5.82s
152:	learn: 0.0537186	total: 661ms	remaining: 5.82s
153:	learn: 0.0535432	total: 665ms	remaining: 5.81s
154:	learn: 0.0533677	total: 670ms	remaining: 5.81s
155:	learn: 0.0531910	total: 674ms	remaining: 5.81s
156:	learn: 0.0530161	total: 679ms	remaining: 5.81s
157:	learn: 0.0528435	total: 683ms	remaining: 5.8s
158:	learn: 0.0526745	total: 688ms	remaining: 5.8s
159:	learn: 0.0525027	total: 693ms	remaining: 5.8s
160:	learn: 0.0523348	total: 697ms	remaining: 5.8s
161:	learn: 0.0521658	total: 702ms	remaining: 5.79s
162:	learn: 0.0520041	total: 706ms	remaining: 5.79s
163:	learn: 0.0518511	total: 711ms	remaining: 5.79s
164:	learn: 0.0516900	total: 715ms	remaining: 5.79s
165:	learn: 0.0515404	total: 720ms	remaining: 5.79s
166:	learn: 0.0513891	total: 725ms	remaining: 5.78s
167:	learn: 0.0512373	total: 729ms	remaining: 5.78s
168:	learn: 0.0510860	total: 734ms	remaining: 5.78s
169:	learn: 0.0509357	total: 738ms	remaining: 5.78s
170:	learn: 0.0507893	total: 743ms	remaining: 5.77s
171:	learn: 0.0506436	total: 747ms	remaining: 5.77s
172:	learn: 0.0505094	total: 752ms	remaining: 5.77s
173:	learn: 0.0503775	total: 756ms	remaining: 5.76s
174:	learn: 0.0502394	total: 761ms	remaining: 5.76s
175:	learn: 0.0501029	total: 765ms	remaining: 5.76s
176:	learn: 0.0499722	total: 770ms	remaining: 5.75s
177:	learn: 0.0498437	total: 775ms	remaining: 5.75s
178:	learn: 0.0497174	total: 779ms	remaining: 5.75s
179:	learn: 0.0495903	total: 784ms	remaining: 5.75s
180:	learn: 0.0494738	total: 789ms	remaining: 5.75s
181:	learn: 0.0493463	total: 793ms	remaining: 5.75s
182:	learn: 0.0492284	total: 798ms	remaining: 5.74s
183:	learn: 0.0491139	total: 802ms	remaining: 5.74s
184:	learn: 0.0490040	total: 807ms	remaining: 5.74s
185:	learn: 0.0488971	total: 812ms	remaining: 5.74s
186:	learn: 0.0487842	total: 817ms	remaining: 5.73s
187:	learn: 0.0486712	total: 821ms	remaining: 5.73s
188:	learn: 0.0485642	total: 826ms	remaining: 5.73s
189:	learn: 0.0484577	total: 830ms	remaining: 5.72s
190:	learn: 0.0483627	total: 835ms	remaining: 5.72s
191:	learn: 0.0482594	total: 839ms	remaining: 5.72s
192:	learn: 0.0481492	total: 844ms	remaining: 5.71s
193:	learn: 0.0480519	total: 848ms	remaining: 5.71s
194:	learn: 0.0479534	total: 853ms	remaining: 5.71s
195:	learn: 0.0478481	total: 857ms	remaining: 5.7s
196:	learn: 0.0477540	total: 862ms	remaining: 5.7s
197:	learn: 0.0476655	total: 866ms	remaining: 5.7s
198:	learn: 0.0475700	total: 871ms	remaining: 5.69s
199:	learn: 0.0474825	total: 875ms	remaining: 5.69s
200:	learn: 0.0473909	total: 880ms	remaining: 5.68s
201:	learn: 0.0472994	total: 884ms	remaining: 5.68s
202:	learn: 0.0472103	total: 889ms	remaining: 5.68s
203:	learn: 0.0471227	total: 893ms	remaining: 5.67s
204:	learn: 0.0470322	total: 898ms	remaining: 5.67s
205:	learn: 0.0469463	total: 902ms	remaining: 5.67s
206:	learn: 0.0468635	total: 907ms	remaining: 5.67s
207:	learn: 0.0467798	total: 912ms	remaining: 5.66s
208:	learn: 0.0466981	total: 916ms	remaining: 5.66s
209:	learn: 0.0466139	total: 921ms	remaining: 5.66s
210:	learn: 0.0465315	total: 925ms	remaining: 5.65s
211:	learn: 0.0464468	total: 930ms	remaining: 5.65s
212:	learn: 0.0463667	total: 934ms	remaining: 5.64s
213:	learn: 0.0462923	total: 939ms	remaining: 5.64s
214:	learn: 0.0462199	total: 943ms	remaining: 5.64s
215:	learn: 0.0461425	total: 948ms	remaining: 5.63s
216:	learn: 0.0460748	total: 953ms	remaining: 5.63s
217:	learn: 0.0460013	total: 957ms	remaining: 5.63s
218:	learn: 0.0459285	total: 962ms	remaining: 5.63s
219:	learn: 0.0458605	total: 966ms	remaining: 5.62s
220:	learn: 0.0457980	total: 971ms	remaining: 5.62s
221:	learn: 0.0457348	total: 975ms	remaining: 5.61s
222:	learn: 0.0456694	total: 980ms	remaining: 5.61s
223:	learn: 0.0456071	total: 984ms	remaining: 5.6s
224:	learn: 0.0455422	total: 988ms	remaining: 5.6s
225:	learn: 0.0454824	total: 993ms	remaining: 5.6s
226:	learn: 0.0454342	total: 995ms	remaining: 5.58s
227:	learn: 0.0453674	total: 1000ms	remaining: 5.58s
228:	learn: 0.0453062	total: 1s	remaining: 5.57s
229:	learn: 0.0452442	total: 1.01s	remaining: 5.57s
230:	learn: 0.0451835	total: 1.01s	remaining: 5.57s
231:	learn: 0.0451249	total: 1.02s	remaining: 5.57s
232:	learn: 0.0450720	total: 1.02s	remaining: 5.56s
233:	learn: 0.0450159	total: 1.03s	remaining: 5.56s
234:	learn: 0.0449584	total: 1.03s	remaining: 5.55s
235:	learn: 0.0448971	total: 1.04s	remaining: 5.55s
236:	learn: 0.0448377	total: 1.04s	remaining: 5.55s
237:	learn: 0.0447886	total: 1.04s	remaining: 5.54s
238:	learn: 0.0447305	total: 1.05s	remaining: 5.54s
239:	learn: 0.0446765	total: 1.05s	remaining: 5.54s
240:	learn: 0.0446216	total: 1.06s	remaining: 5.53s
241:	learn: 0.0445788	total: 1.06s	remaining: 5.53s
242:	learn: 0.0445319	total: 1.07s	remaining: 5.53s
243:	learn: 0.0444808	total: 1.07s	remaining: 5.52s
244:	learn: 0.0444355	total: 1.08s	remaining: 5.52s
245:	learn: 0.0443885	total: 1.08s	remaining: 5.51s
246:	learn: 0.0443423	total: 1.09s	remaining: 5.51s
247:	learn: 0.0443092	total: 1.09s	remaining: 5.5s
248:	learn: 0.0442625	total: 1.09s	remaining: 5.49s
249:	learn: 0.0442171	total: 1.1s	remaining: 5.49s
250:	learn: 0.0441822	total: 1.1s	remaining: 5.48s
251:	learn: 0.0441362	total: 1.11s	remaining: 5.48s
252:	learn: 0.0440905	total: 1.11s	remaining: 5.47s
253:	learn: 0.0440559	total: 1.11s	remaining: 5.47s
254:	learn: 0.0440182	total: 1.12s	remaining: 5.47s
255:	learn: 0.0439744	total: 1.12s	remaining: 5.46s
256:	learn: 0.0439380	total: 1.13s	remaining: 5.46s
257:	learn: 0.0439093	total: 1.13s	remaining: 5.45s
258:	learn: 0.0438677	total: 1.14s	remaining: 5.44s
259:	learn: 0.0438297	total: 1.14s	remaining: 5.44s
260:	learn: 0.0437963	total: 1.15s	remaining: 5.44s
261:	learn: 0.0437645	total: 1.15s	remaining: 5.43s
262:	learn: 0.0437267	total: 1.15s	remaining: 5.43s
263:	learn: 0.0436935	total: 1.16s	remaining: 5.42s
264:	learn: 0.0436509	total: 1.16s	remaining: 5.42s
265:	learn: 0.0436108	total: 1.17s	remaining: 5.42s
266:	learn: 0.0435785	total: 1.17s	remaining: 5.42s
267:	learn: 0.0435475	total: 1.18s	remaining: 5.41s
268:	learn: 0.0435175	total: 1.18s	remaining: 5.41s
269:	learn: 0.0434823	total: 1.19s	remaining: 5.4s
270:	learn: 0.0434511	total: 1.19s	remaining: 5.4s
271:	learn: 0.0434179	total: 1.2s	remaining: 5.4s
272:	learn: 0.0433824	total: 1.2s	remaining: 5.39s
273:	learn: 0.0433525	total: 1.21s	remaining: 5.39s
274:	learn: 0.0433228	total: 1.21s	remaining: 5.39s
275:	learn: 0.0432927	total: 1.21s	remaining: 5.39s
276:	learn: 0.0432636	total: 1.22s	remaining: 5.38s
277:	learn: 0.0432299	total: 1.22s	remaining: 5.38s
278:	learn: 0.0431961	total: 1.23s	remaining: 5.38s
279:	learn: 0.0431713	total: 1.23s	remaining: 5.37s
280:	learn: 0.0431400	total: 1.24s	remaining: 5.37s
281:	learn: 0.0431133	total: 1.24s	remaining: 5.37s
282:	learn: 0.0430812	total: 1.25s	remaining: 5.36s
283:	learn: 0.0430517	total: 1.25s	remaining: 5.36s
284:	learn: 0.0430190	total: 1.26s	remaining: 5.36s
285:	learn: 0.0429905	total: 1.26s	remaining: 5.35s
286:	learn: 0.0429623	total: 1.26s	remaining: 5.35s
287:	learn: 0.0429356	total: 1.27s	remaining: 5.34s
288:	learn: 0.0429124	total: 1.27s	remaining: 5.34s
289:	learn: 0.0428871	total: 1.28s	remaining: 5.34s
290:	learn: 0.0428611	total: 1.28s	remaining: 5.33s
291:	learn: 0.0428336	total: 1.29s	remaining: 5.33s
292:	learn: 0.0428082	total: 1.29s	remaining: 5.33s
293:	learn: 0.0427810	total: 1.3s	remaining: 5.32s
294:	learn: 0.0427648	total: 1.3s	remaining: 5.31s
295:	learn: 0.0427426	total: 1.3s	remaining: 5.31s
296:	learn: 0.0427186	total: 1.31s	remaining: 5.3s
297:	learn: 0.0426940	total: 1.31s	remaining: 5.3s
298:	learn: 0.0426653	total: 1.32s	remaining: 5.3s
299:	learn: 0.0426412	total: 1.32s	remaining: 5.29s
300:	learn: 0.0426205	total: 1.33s	remaining: 5.29s
301:	learn: 0.0425976	total: 1.33s	remaining: 5.29s
302:	learn: 0.0425769	total: 1.34s	remaining: 5.28s
303:	learn: 0.0425512	total: 1.34s	remaining: 5.28s
304:	learn: 0.0425326	total: 1.35s	remaining: 5.28s
305:	learn: 0.0425053	total: 1.35s	remaining: 5.27s
306:	learn: 0.0424828	total: 1.36s	remaining: 5.27s
307:	learn: 0.0424629	total: 1.36s	remaining: 5.27s
308:	learn: 0.0424438	total: 1.36s	remaining: 5.26s
309:	learn: 0.0424209	total: 1.37s	remaining: 5.26s
310:	learn: 0.0424021	total: 1.37s	remaining: 5.25s
311:	learn: 0.0423851	total: 1.38s	remaining: 5.25s
312:	learn: 0.0423652	total: 1.38s	remaining: 5.25s
313:	learn: 0.0423500	total: 1.39s	remaining: 5.24s
314:	learn: 0.0423267	total: 1.39s	remaining: 5.24s
315:	learn: 0.0423086	total: 1.4s	remaining: 5.23s
316:	learn: 0.0422867	total: 1.4s	remaining: 5.23s
317:	learn: 0.0422649	total: 1.41s	remaining: 5.22s
318:	learn: 0.0422454	total: 1.41s	remaining: 5.22s
319:	learn: 0.0422290	total: 1.42s	remaining: 5.22s
320:	learn: 0.0422119	total: 1.42s	remaining: 5.21s
321:	learn: 0.0421932	total: 1.42s	remaining: 5.21s
322:	learn: 0.0421731	total: 1.43s	remaining: 5.21s
323:	learn: 0.0421561	total: 1.43s	remaining: 5.2s
324:	learn: 0.0421369	total: 1.44s	remaining: 5.2s
325:	learn: 0.0421226	total: 1.44s	remaining: 5.2s
326:	learn: 0.0421050	total: 1.45s	remaining: 5.19s
327:	learn: 0.0420879	total: 1.45s	remaining: 5.19s
328:	learn: 0.0420724	total: 1.46s	remaining: 5.18s
329:	learn: 0.0420531	total: 1.46s	remaining: 5.18s
330:	learn: 0.0420391	total: 1.47s	remaining: 5.18s
331:	learn: 0.0420245	total: 1.47s	remaining: 5.17s
332:	learn: 0.0420095	total: 1.48s	remaining: 5.17s
333:	learn: 0.0419940	total: 1.48s	remaining: 5.17s
334:	learn: 0.0419808	total: 1.48s	remaining: 5.16s
335:	learn: 0.0419654	total: 1.49s	remaining: 5.16s
336:	learn: 0.0419478	total: 1.49s	remaining: 5.15s
337:	learn: 0.0419335	total: 1.5s	remaining: 5.15s
338:	learn: 0.0419158	total: 1.5s	remaining: 5.15s
339:	learn: 0.0419010	total: 1.51s	remaining: 5.14s
340:	learn: 0.0418850	total: 1.51s	remaining: 5.14s
341:	learn: 0.0418719	total: 1.52s	remaining: 5.13s
342:	learn: 0.0418582	total: 1.52s	remaining: 5.13s
343:	learn: 0.0418435	total: 1.52s	remaining: 5.13s
344:	learn: 0.0418238	total: 1.53s	remaining: 5.12s
345:	learn: 0.0418099	total: 1.53s	remaining: 5.12s
346:	learn: 0.0417982	total: 1.54s	remaining: 5.12s
347:	learn: 0.0417854	total: 1.54s	remaining: 5.11s
348:	learn: 0.0417690	total: 1.55s	remaining: 5.11s
349:	learn: 0.0417513	total: 1.55s	remaining: 5.11s
350:	learn: 0.0417404	total: 1.56s	remaining: 5.1s
351:	learn: 0.0417262	total: 1.56s	remaining: 5.1s
352:	learn: 0.0417135	total: 1.57s	remaining: 5.09s
353:	learn: 0.0417005	total: 1.57s	remaining: 5.09s
354:	learn: 0.0416889	total: 1.58s	remaining: 5.09s
355:	learn: 0.0416718	total: 1.58s	remaining: 5.08s
356:	learn: 0.0416611	total: 1.59s	remaining: 5.08s
357:	learn: 0.0416450	total: 1.59s	remaining: 5.08s
358:	learn: 0.0416334	total: 1.59s	remaining: 5.07s
359:	learn: 0.0416231	total: 1.6s	remaining: 5.07s
360:	learn: 0.0416112	total: 1.6s	remaining: 5.06s
361:	learn: 0.0415994	total: 1.61s	remaining: 5.06s
362:	learn: 0.0415861	total: 1.61s	remaining: 5.06s
363:	learn: 0.0415751	total: 1.62s	remaining: 5.05s
364:	learn: 0.0415611	total: 1.62s	remaining: 5.05s
365:	learn: 0.0415502	total: 1.63s	remaining: 5.04s
366:	learn: 0.0415353	total: 1.63s	remaining: 5.04s
367:	learn: 0.0415233	total: 1.64s	remaining: 5.04s
368:	learn: 0.0415109	total: 1.64s	remaining: 5.03s
369:	learn: 0.0415014	total: 1.65s	remaining: 5.03s
370:	learn: 0.0414862	total: 1.65s	remaining: 5.02s
371:	learn: 0.0414754	total: 1.66s	remaining: 5.02s
372:	learn: 0.0414660	total: 1.66s	remaining: 5.02s
373:	learn: 0.0414566	total: 1.66s	remaining: 5.01s
374:	learn: 0.0414471	total: 1.67s	remaining: 5.01s
375:	learn: 0.0414352	total: 1.67s	remaining: 5s
376:	learn: 0.0414262	total: 1.68s	remaining: 5s
377:	learn: 0.0414128	total: 1.68s	remaining: 5s
378:	learn: 0.0414038	total: 1.69s	remaining: 4.99s
379:	learn: 0.0413905	total: 1.69s	remaining: 4.99s
380:	learn: 0.0413829	total: 1.7s	remaining: 4.98s
381:	learn: 0.0413735	total: 1.7s	remaining: 4.98s
382:	learn: 0.0413646	total: 1.71s	remaining: 4.98s
383:	learn: 0.0413566	total: 1.71s	remaining: 4.97s
384:	learn: 0.0413475	total: 1.72s	remaining: 4.97s
385:	learn: 0.0413358	total: 1.72s	remaining: 4.96s
386:	learn: 0.0413243	total: 1.72s	remaining: 4.96s

In [197]:
s=pd.read_csv('Processed Test Data.csv')
s

,spatial__geohash,StandardScaler__Temperature,remainder__timestamp,remainder__RoadType,remainder__NumberofLanes,remainder__LargeVehicles
0,0.040119,0.496822,2.25,1,1,1
1,0.031792,0.338859,2.25,1,1,1
2,0.029433,0.589577,2.25,1,3,0
3,0.040028,0.496822,2.25,1,2,1
4,0.054634,0.525448,2.25,1,1,1
...,...,...,...,...,...,...
41773,0.138812,0.546384,13.75,2,1,1
41774,0.113154,0.406268,13.75,1,2,1
41775,0.018080,0.445646,13.75,1,2,1
41776,0.075093,0.434365,13.75,1,2,1
41777,0.019511,0.558644,13.75,1,2,1

In [198]:
o=model_submit.predict(s)

In [199]:
o=pd.DataFrame(o,columns=['demand'])

In [200]:
r=pd.read_csv('dataset copy/test.csv')

In [201]:
r=r['Index']

In [202]:
r=pd.DataFrame(r)

In [203]:
r['demand']=o
r

       Index    demand
0          0  0.043849
1          1  0.038987
2          2  0.035088
3          3  0.041517
4          4  0.057215
...      ...       ...
41773  41773  0.275906
41774  41774  0.130679
41775  41775  0.014172
41776  41776  0.076256
41777  41777  0.017921

[41778 rows x 2 columns]

In [204]:
r.to_csv('submission.csv',index=False)

# More models

In [191]:
model2=CatBoostRegressor(depth=10,iterations=1500,learning_rate=0.01)
model2.fit(x_train,y_train)

y_pred2=model2.predict(x_test)
r2_score(y_test,y_pred2)

0:	learn: 0.1409433	total: 3.6ms	remaining: 5.4s
1:	learn: 0.1397710	total: 11.8ms	remaining: 8.86s
2:	learn: 0.1385669	total: 15.5ms	remaining: 7.72s
3:	learn: 0.1373935	total: 18.5ms	remaining: 6.92s
4:	learn: 0.1362125	total: 23.1ms	remaining: 6.91s
5:	learn: 0.1350757	total: 25.3ms	remaining: 6.31s
6:	learn: 0.1339617	total: 32.2ms	remaining: 6.87s
7:	learn: 0.1328084	total: 38.7ms	remaining: 7.22s
8:	learn: 0.1316994	total: 45.2ms	remaining: 7.49s
9:	learn: 0.1306049	total: 51.4ms	remaining: 7.65s
10:	learn: 0.1295121	total: 57.7ms	remaining: 7.81s
11:	learn: 0.1284217	total: 64ms	remaining: 7.93s
12:	learn: 0.1273537	total: 67.6ms	remaining: 7.74s
13:	learn: 0.1262701	total: 74.2ms	remaining: 7.88s
14:	learn: 0.1252408	total: 77ms	remaining: 7.62s
15:	learn: 0.1242148	total: 81.6ms	remaining: 7.57s
16:	learn: 0.1231858	total: 84.5ms	remaining: 7.37s
17:	learn: 0.1221869	total: 90.6ms	remaining: 7.46s
18:	learn: 0.1211978	total: 93ms	remaining: 7.25s
19:	learn: 0.1202087	total: 99.5ms	remaining: 7.36s
20:	learn: 0.1192517	total: 103ms	remaining: 7.26s
21:	learn: 0.1182742	total: 109ms	remaining: 7.34s
22:	learn: 0.1173158	total: 115ms	remaining: 7.42s
23:	learn: 0.1163560	total: 122ms	remaining: 7.52s
24:	learn: 0.1154005	total: 129ms	remaining: 7.58s
25:	learn: 0.1144561	total: 135ms	remaining: 7.64s
26:	learn: 0.1135620	total: 138ms	remaining: 7.52s
27:	learn: 0.1126470	total: 145ms	remaining: 7.6s
28:	learn: 0.1117429	total: 151ms	remaining: 7.65s
29:	learn: 0.1108443	total: 155ms	remaining: 7.61s
30:	learn: 0.1099909	total: 158ms	remaining: 7.48s
31:	learn: 0.1091425	total: 161ms	remaining: 7.38s
32:	learn: 0.1082703	total: 167ms	remaining: 7.43s
33:	learn: 0.1074122	total: 173ms	remaining: 7.47s
34:	learn: 0.1065669	total: 180ms	remaining: 7.54s
35:	learn: 0.1057362	total: 186ms	remaining: 7.58s
36:	learn: 0.1048983	total: 193ms	remaining: 7.63s
37:	learn: 0.1041167	total: 195ms	remaining: 7.51s
38:	learn: 0.1032982	total: 202ms	remaining: 7.55s
39:	learn: 0.1025148	total: 209ms	remaining: 7.62s
40:	learn: 0.1017203	total: 215ms	remaining: 7.66s
41:	learn: 0.1009624	total: 218ms	remaining: 7.58s
42:	learn: 0.1002040	total: 226ms	remaining: 7.65s
43:	learn: 0.0994233	total: 232ms	remaining: 7.68s
44:	learn: 0.0986835	total: 239ms	remaining: 7.71s
45:	learn: 0.0979271	total: 245ms	remaining: 7.74s
46:	learn: 0.0972003	total: 249ms	remaining: 7.71s
47:	learn: 0.0964753	total: 256ms	remaining: 7.75s
48:	learn: 0.0957593	total: 263ms	remaining: 7.8s
49:	learn: 0.0950649	total: 271ms	remaining: 7.85s
50:	learn: 0.0943553	total: 278ms	remaining: 7.89s
51:	learn: 0.0936529	total: 284ms	remaining: 7.92s
52:	learn: 0.0929792	total: 291ms	remaining: 7.95s
53:	learn: 0.0922942	total: 298ms	remaining: 7.99s
54:	learn: 0.0916404	total: 305ms	remaining: 8.02s
55:	learn: 0.0909789	total: 312ms	remaining: 8.04s
56:	learn: 0.0903234	total: 319ms	remaining: 8.09s
57:	learn: 0.0896740	total: 326ms	remaining: 8.12s
58:	learn: 0.0890696	total: 334ms	remaining: 8.15s
59:	learn: 0.0884263	total: 341ms	remaining: 8.19s
60:	learn: 0.0878078	total: 349ms	remaining: 8.22s
61:	learn: 0.0871810	total: 356ms	remaining: 8.26s
62:	learn: 0.0865580	total: 363ms	remaining: 8.29s
63:	learn: 0.0859504	total: 370ms	remaining: 8.31s
64:	learn: 0.0853517	total: 378ms	remaining: 8.34s
65:	learn: 0.0847522	total: 385ms	remaining: 8.36s
66:	learn: 0.0841674	total: 392ms	remaining: 8.38s
67:	learn: 0.0835949	total: 397ms	remaining: 8.37s
68:	learn: 0.0830323	total: 406ms	remaining: 8.41s
69:	learn: 0.0824624	total: 414ms	remaining: 8.46s
70:	learn: 0.0819001	total: 423ms	remaining: 8.5s
71:	learn: 0.0813540	total: 430ms	remaining: 8.52s
72:	learn: 0.0808241	total: 437ms	remaining: 8.54s
73:	learn: 0.0802796	total: 445ms	remaining: 8.57s
74:	learn: 0.0797505	total: 452ms	remaining: 8.59s
75:	learn: 0.0792312	total: 459ms	remaining: 8.6s
76:	learn: 0.0787196	total: 466ms	remaining: 8.62s
77:	learn: 0.0782179	total: 474ms	remaining: 8.63s
78:	learn: 0.0777066	total: 481ms	remaining: 8.65s
79:	learn: 0.0772127	total: 488ms	remaining: 8.66s
80:	learn: 0.0767085	total: 496ms	remaining: 8.69s
81:	learn: 0.0762221	total: 504ms	remaining: 8.71s
82:	learn: 0.0757485	total: 508ms	remaining: 8.67s
83:	learn: 0.0752707	total: 515ms	remaining: 8.68s
84:	learn: 0.0748043	total: 522ms	remaining: 8.69s
85:	learn: 0.0743383	total: 529ms	remaining: 8.7s
86:	learn: 0.0738769	total: 537ms	remaining: 8.71s
87:	learn: 0.0734325	total: 544ms	remaining: 8.72s
88:	learn: 0.0729932	total: 551ms	remaining: 8.74s
89:	learn: 0.0725609	total: 556ms	remaining: 8.71s
90:	learn: 0.0721370	total: 561ms	remaining: 8.68s
91:	learn: 0.0717022	total: 568ms	remaining: 8.69s
92:	learn: 0.0712779	total: 573ms	remaining: 8.67s
93:	learn: 0.0708587	total: 580ms	remaining: 8.68s
94:	learn: 0.0704483	total: 587ms	remaining: 8.69s
95:	learn: 0.0700616	total: 592ms	remaining: 8.65s
96:	learn: 0.0696578	total: 599ms	remaining: 8.66s
97:	learn: 0.0692611	total: 606ms	remaining: 8.67s
98:	learn: 0.0688678	total: 613ms	remaining: 8.68s
99:	learn: 0.0684826	total: 620ms	remaining: 8.69s
100:	learn: 0.0681019	total: 628ms	remaining: 8.7s
101:	learn: 0.0677185	total: 635ms	remaining: 8.71s
102:	learn: 0.0673326	total: 643ms	remaining: 8.72s
103:	learn: 0.0669844	total: 646ms	remaining: 8.67s
104:	learn: 0.0666153	total: 653ms	remaining: 8.68s
105:	learn: 0.0662672	total: 659ms	remaining: 8.66s
106:	learn: 0.0659158	total: 666ms	remaining: 8.67s
107:	learn: 0.0655542	total: 673ms	remaining: 8.67s
108:	learn: 0.0652159	total: 680ms	remaining: 8.68s
109:	learn: 0.0648751	total: 687ms	remaining: 8.68s
110:	learn: 0.0645312	total: 694ms	remaining: 8.68s
111:	learn: 0.0642162	total: 701ms	remaining: 8.69s
112:	learn: 0.0638866	total: 708ms	remaining: 8.69s
113:	learn: 0.0635714	total: 715ms	remaining: 8.7s
114:	learn: 0.0632619	total: 719ms	remaining: 8.66s
115:	learn: 0.0629472	total: 726ms	remaining: 8.67s
116:	learn: 0.0626462	total: 733ms	remaining: 8.67s
117:	learn: 0.0623399	total: 740ms	remaining: 8.67s
118:	learn: 0.0620434	total: 747ms	remaining: 8.67s
119:	learn: 0.0617434	total: 754ms	remaining: 8.67s
120:	learn: 0.0614597	total: 761ms	remaining: 8.67s
121:	learn: 0.0611642	total: 768ms	remaining: 8.68s
122:	learn: 0.0608659	total: 775ms	remaining: 8.68s
123:	learn: 0.0605806	total: 782ms	remaining: 8.68s
124:	learn: 0.0603212	total: 785ms	remaining: 8.64s
125:	learn: 0.0600484	total: 792ms	remaining: 8.64s
126:	learn: 0.0597818	total: 799ms	remaining: 8.64s
127:	learn: 0.0595141	total: 806ms	remaining: 8.64s
128:	learn: 0.0592413	total: 813ms	remaining: 8.64s
129:	learn: 0.0589775	total: 820ms	remaining: 8.64s
130:	learn: 0.0587110	total: 827ms	remaining: 8.64s
131:	learn: 0.0584584	total: 835ms	remaining: 8.65s
132:	learn: 0.0582086	total: 842ms	remaining: 8.65s
133:	learn: 0.0579552	total: 849ms	remaining: 8.65s
134:	learn: 0.0577123	total: 856ms	remaining: 8.65s
135:	learn: 0.0574732	total: 863ms	remaining: 8.65s
136:	learn: 0.0572352	total: 871ms	remaining: 8.66s
137:	learn: 0.0570127	total: 878ms	remaining: 8.66s
138:	learn: 0.0567822	total: 885ms	remaining: 8.66s
139:	learn: 0.0565665	total: 889ms	remaining: 8.64s
140:	learn: 0.0563425	total: 897ms	remaining: 8.64s
141:	learn: 0.0561269	total: 902ms	remaining: 8.63s
142:	learn: 0.0559105	total: 909ms	remaining: 8.63s
143:	learn: 0.0557007	total: 916ms	remaining: 8.63s
144:	learn: 0.0554922	total: 924ms	remaining: 8.63s
145:	learn: 0.0552921	total: 931ms	remaining: 8.63s
146:	learn: 0.0550852	total: 937ms	remaining: 8.63s
147:	learn: 0.0548778	total: 945ms	remaining: 8.63s
148:	learn: 0.0546721	total: 952ms	remaining: 8.63s
149:	learn: 0.0544779	total: 959ms	remaining: 8.63s
150:	learn: 0.0542819	total: 966ms	remaining: 8.63s
151:	learn: 0.0540930	total: 973ms	remaining: 8.63s
152:	learn: 0.0539054	total: 980ms	remaining: 8.62s
153:	learn: 0.0537110	total: 986ms	remaining: 8.62s
154:	learn: 0.0535251	total: 994ms	remaining: 8.62s
155:	learn: 0.0533485	total: 1s	remaining: 8.62s
156:	learn: 0.0531747	total: 1.01s	remaining: 8.62s
157:	learn: 0.0529995	total: 1.01s	remaining: 8.61s
158:	learn: 0.0528182	total: 1.02s	remaining: 8.61s
159:	learn: 0.0526534	total: 1.03s	remaining: 8.61s
160:	learn: 0.0524845	total: 1.03s	remaining: 8.61s
161:	learn: 0.0523175	total: 1.04s	remaining: 8.61s
162:	learn: 0.0521572	total: 1.05s	remaining: 8.62s
163:	learn: 0.0519916	total: 1.06s	remaining: 8.62s
164:	learn: 0.0518436	total: 1.06s	remaining: 8.59s
165:	learn: 0.0516840	total: 1.07s	remaining: 8.59s
166:	learn: 0.0515372	total: 1.08s	remaining: 8.59s
167:	learn: 0.0513862	total: 1.08s	remaining: 8.59s
168:	learn: 0.0512402	total: 1.09s	remaining: 8.59s
169:	learn: 0.0510988	total: 1.1s	remaining: 8.59s
170:	learn: 0.0509589	total: 1.1s	remaining: 8.59s
171:	learn: 0.0508232	total: 1.11s	remaining: 8.58s
172:	learn: 0.0506824	total: 1.12s	remaining: 8.58s
173:	learn: 0.0505469	total: 1.13s	remaining: 8.58s
174:	learn: 0.0504179	total: 1.13s	remaining: 8.58s
175:	learn: 0.0502846	total: 1.14s	remaining: 8.57s
176:	learn: 0.0501485	total: 1.15s	remaining: 8.57s
177:	learn: 0.0500174	total: 1.15s	remaining: 8.57s
178:	learn: 0.0498844	total: 1.16s	remaining: 8.57s
179:	learn: 0.0497573	total: 1.17s	remaining: 8.57s
180:	learn: 0.0496342	total: 1.17s	remaining: 8.56s
181:	learn: 0.0495076	total: 1.18s	remaining: 8.56s
182:	learn: 0.0493872	total: 1.19s	remaining: 8.55s
183:	learn: 0.0492667	total: 1.2s	remaining: 8.55s
184:	learn: 0.0491540	total: 1.2s	remaining: 8.55s
185:	learn: 0.0490307	total: 1.21s	remaining: 8.54s
186:	learn: 0.0489145	total: 1.22s	remaining: 8.54s
187:	learn: 0.0487996	total: 1.22s	remaining: 8.54s
188:	learn: 0.0486882	total: 1.23s	remaining: 8.54s
189:	learn: 0.0485812	total: 1.24s	remaining: 8.53s
190:	learn: 0.0484717	total: 1.25s	remaining: 8.53s
191:	learn: 0.0483640	total: 1.25s	remaining: 8.53s
192:	learn: 0.0482667	total: 1.26s	remaining: 8.53s
193:	learn: 0.0481658	total: 1.27s	remaining: 8.52s
194:	learn: 0.0480665	total: 1.27s	remaining: 8.52s
195:	learn: 0.0479672	total: 1.28s	remaining: 8.52s
196:	learn: 0.0478685	total: 1.29s	remaining: 8.52s
197:	learn: 0.0477678	total: 1.29s	remaining: 8.52s
198:	learn: 0.0476829	total: 1.3s	remaining: 8.49s
199:	learn: 0.0475870	total: 1.31s	remaining: 8.49s
200:	learn: 0.0475019	total: 1.31s	remaining: 8.49s
201:	learn: 0.0474135	total: 1.32s	remaining: 8.49s
202:	learn: 0.0473200	total: 1.33s	remaining: 8.49s
203:	learn: 0.0472327	total: 1.33s	remaining: 8.48s
204:	learn: 0.0471496	total: 1.34s	remaining: 8.48s
205:	learn: 0.0470571	total: 1.35s	remaining: 8.48s
206:	learn: 0.0469867	total: 1.35s	remaining: 8.46s
207:	learn: 0.0469095	total: 1.36s	remaining: 8.46s
208:	learn: 0.0468421	total: 1.36s	remaining: 8.43s
209:	learn: 0.0467534	total: 1.37s	remaining: 8.43s
210:	learn: 0.0466758	total: 1.38s	remaining: 8.42s
211:	learn: 0.0465953	total: 1.39s	remaining: 8.41s
212:	learn: 0.0465301	total: 1.39s	remaining: 8.39s
213:	learn: 0.0464590	total: 1.4s	remaining: 8.39s
214:	learn: 0.0463854	total: 1.4s	remaining: 8.39s
215:	learn: 0.0463123	total: 1.41s	remaining: 8.38s
216:	learn: 0.0462416	total: 1.42s	remaining: 8.38s
217:	learn: 0.0461596	total: 1.42s	remaining: 8.38s
218:	learn: 0.0460918	total: 1.43s	remaining: 8.38s
219:	learn: 0.0460186	total: 1.44s	remaining: 8.37s
220:	learn: 0.0459527	total: 1.45s	remaining: 8.37s
221:	learn: 0.0458848	total: 1.45s	remaining: 8.37s
222:	learn: 0.0458320	total: 1.46s	remaining: 8.35s
223:	learn: 0.0457601	total: 1.46s	remaining: 8.34s
224:	learn: 0.0456894	total: 1.47s	remaining: 8.34s
225:	learn: 0.0456242	total: 1.48s	remaining: 8.34s
226:	learn: 0.0455592	total: 1.49s	remaining: 8.33s
227:	learn: 0.0454966	total: 1.49s	remaining: 8.33s
228:	learn: 0.0454336	total: 1.5s	remaining: 8.33s
229:	learn: 0.0453726	total: 1.51s	remaining: 8.32s
230:	learn: 0.0453154	total: 1.51s	remaining: 8.32s
231:	learn: 0.0452546	total: 1.52s	remaining: 8.31s
232:	learn: 0.0451989	total: 1.53s	remaining: 8.31s
233:	learn: 0.0451356	total: 1.53s	remaining: 8.31s
234:	learn: 0.0450869	total: 1.54s	remaining: 8.3s
235:	learn: 0.0450301	total: 1.55s	remaining: 8.29s
236:	learn: 0.0449759	total: 1.56s	remaining: 8.29s
237:	learn: 0.0449255	total: 1.56s	remaining: 8.29s
238:	learn: 0.0448745	total: 1.57s	remaining: 8.28s
239:	learn: 0.0448258	total: 1.58s	remaining: 8.28s
240:	learn: 0.0447765	total: 1.58s	remaining: 8.27s
241:	learn: 0.0447301	total: 1.59s	remaining: 8.27s
242:	learn: 0.0446805	total: 1.6s	remaining: 8.27s
243:	learn: 0.0446315	total: 1.61s	remaining: 8.27s
244:	learn: 0.0445852	total: 1.61s	remaining: 8.27s
245:	learn: 0.0445400	total: 1.62s	remaining: 8.27s
246:	learn: 0.0444999	total: 1.63s	remaining: 8.27s
247:	learn: 0.0444549	total: 1.64s	remaining: 8.27s
248:	learn: 0.0444014	total: 1.65s	remaining: 8.27s
249:	learn: 0.0443510	total: 1.66s	remaining: 8.28s
250:	learn: 0.0443056	total: 1.66s	remaining: 8.28s
251:	learn: 0.0442518	total: 1.67s	remaining: 8.28s
252:	learn: 0.0442072	total: 1.68s	remaining: 8.27s
253:	learn: 0.0441586	total: 1.69s	remaining: 8.27s
254:	learn: 0.0441162	total: 1.69s	remaining: 8.27s
255:	learn: 0.0440714	total: 1.7s	remaining: 8.26s
256:	learn: 0.0440333	total: 1.71s	remaining: 8.26s
257:	learn: 0.0439923	total: 1.71s	remaining: 8.25s
258:	learn: 0.0439483	total: 1.72s	remaining: 8.25s
259:	learn: 0.0439059	total: 1.73s	remaining: 8.25s
260:	learn: 0.0438659	total: 1.74s	remaining: 8.24s
261:	learn: 0.0438264	total: 1.74s	remaining: 8.24s
262:	learn: 0.0438011	total: 1.75s	remaining: 8.21s
263:	learn: 0.0437601	total: 1.75s	remaining: 8.21s
264:	learn: 0.0437221	total: 1.76s	remaining: 8.21s
265:	learn: 0.0436882	total: 1.77s	remaining: 8.2s
266:	learn: 0.0436481	total: 1.77s	remaining: 8.2s
267:	learn: 0.0436060	total: 1.78s	remaining: 8.19s
268:	learn: 0.0435718	total: 1.79s	remaining: 8.19s
269:	learn: 0.0435361	total: 1.8s	remaining: 8.18s
270:	learn: 0.0435028	total: 1.8s	remaining: 8.18s
271:	learn: 0.0434685	total: 1.81s	remaining: 8.17s
272:	learn: 0.0434333	total: 1.82s	remaining: 8.17s
273:	learn: 0.0433929	total: 1.82s	remaining: 8.16s
274:	learn: 0.0433620	total: 1.83s	remaining: 8.16s
275:	learn: 0.0433392	total: 1.83s	remaining: 8.14s
276:	learn: 0.0433048	total: 1.84s	remaining: 8.13s
277:	learn: 0.0432671	total: 1.85s	remaining: 8.13s
278:	learn: 0.0432358	total: 1.86s	remaining: 8.12s
279:	learn: 0.0432162	total: 1.86s	remaining: 8.1s
280:	learn: 0.0431902	total: 1.87s	remaining: 8.1s
281:	learn: 0.0431685	total: 1.87s	remaining: 8.08s
282:	learn: 0.0431371	total: 1.88s	remaining: 8.07s
283:	learn: 0.0431102	total: 1.88s	remaining: 8.07s
284:	learn: 0.0430779	total: 1.89s	remaining: 8.06s
285:	learn: 0.0430542	total: 1.9s	remaining: 8.06s
286:	learn: 0.0430241	total: 1.91s	remaining: 8.05s
287:	learn: 0.0429936	total: 1.91s	remaining: 8.05s
288:	learn: 0.0429703	total: 1.92s	remaining: 8.04s
289:	learn: 0.0429468	total: 1.93s	remaining: 8.04s
290:	learn: 0.0429158	total: 1.93s	remaining: 8.03s
291:	learn: 0.0428830	total: 1.94s	remaining: 8.03s
292:	learn: 0.0428554	total: 1.95s	remaining: 8.02s
293:	learn: 0.0428320	total: 1.95s	remaining: 8.02s
294:	learn: 0.0428054	total: 1.96s	remaining: 8.01s
295:	learn: 0.0427819	total: 1.97s	remaining: 8.01s
296:	learn: 0.0427589	total: 1.97s	remaining: 8s
297:	learn: 0.0427357	total: 1.98s	remaining: 7.99s
298:	learn: 0.0427055	total: 1.99s	remaining: 7.99s
299:	learn: 0.0426813	total: 2s	remaining: 7.98s
300:	learn: 0.0426578	total: 2s	remaining: 7.98s
301:	learn: 0.0426384	total: 2.01s	remaining: 7.97s
302:	learn: 0.0426137	total: 2.02s	remaining: 7.96s
303:	learn: 0.0425929	total: 2.02s	remaining: 7.96s
304:	learn: 0.0425799	total: 2.03s	remaining: 7.94s
305:	learn: 0.0425535	total: 2.03s	remaining: 7.93s
306:	learn: 0.0425288	total: 2.04s	remaining: 7.93s
307:	learn: 0.0425075	total: 2.05s	remaining: 7.92s
308:	learn: 0.0424846	total: 2.06s	remaining: 7.92s
309:	learn: 0.0424666	total: 2.06s	remaining: 7.92s
310:	learn: 0.0424471	total: 2.07s	remaining: 7.91s
311:	learn: 0.0424270	total: 2.08s	remaining: 7.91s
312:	learn: 0.0424020	total: 2.08s	remaining: 7.9s
313:	learn: 0.0423824	total: 2.09s	remaining: 7.9s
314:	learn: 0.0423618	total: 2.1s	remaining: 7.89s
315:	learn: 0.0423391	total: 2.1s	remaining: 7.89s
316:	learn: 0.0423155	total: 2.11s	remaining: 7.88s
317:	learn: 0.0422981	total: 2.12s	remaining: 7.88s
318:	learn: 0.0422776	total: 2.13s	remaining: 7.87s
319:	learn: 0.0422583	total: 2.13s	remaining: 7.87s
320:	learn: 0.0422352	total: 2.14s	remaining: 7.86s
321:	learn: 0.0422123	total: 2.15s	remaining: 7.86s
322:	learn: 0.0421961	total: 2.15s	remaining: 7.85s
323:	learn: 0.0421806	total: 2.16s	remaining: 7.85s
324:	learn: 0.0421608	total: 2.17s	remaining: 7.84s
325:	learn: 0.0421416	total: 2.17s	remaining: 7.83s
326:	learn: 0.0421239	total: 2.18s	remaining: 7.83s
327:	learn: 0.0421093	total: 2.19s	remaining: 7.83s
328:	learn: 0.0420903	total: 2.2s	remaining: 7.82s
329:	learn: 0.0420744	total: 2.2s	remaining: 7.81s
330:	learn: 0.0420591	total: 2.21s	remaining: 7.81s
331:	learn: 0.0420442	total: 2.22s	remaining: 7.8s
332:	learn: 0.0420274	total: 2.22s	remaining: 7.8s
333:	learn: 0.0420134	total: 2.23s	remaining: 7.79s
334:	learn: 0.0420009	total: 2.24s	remaining: 7.79s
335:	learn: 0.0419813	total: 2.25s	remaining: 7.78s
336:	learn: 0.0419661	total: 2.25s	remaining: 7.77s
337:	learn: 0.0419503	total: 2.26s	remaining: 7.77s
338:	learn: 0.0419362	total: 2.27s	remaining: 7.78s
339:	learn: 0.0419201	total: 2.28s	remaining: 7.78s
340:	learn: 0.0419041	total: 2.29s	remaining: 7.78s
341:	learn: 0.0418847	total: 2.29s	remaining: 7.77s
342:	learn: 0.0418711	total: 2.3s	remaining: 7.77s
343:	learn: 0.0418575	total: 2.31s	remaining: 7.76s
344:	learn: 0.0418503	total: 2.31s	remaining: 7.74s
345:	learn: 0.0418327	total: 2.32s	remaining: 7.74s
346:	learn: 0.0418197	total: 2.33s	remaining: 7.73s
347:	learn: 0.0418034	total: 2.33s	remaining: 7.72s
348:	learn: 0.0417910	total: 2.34s	remaining: 7.72s
349:	learn: 0.0417788	total: 2.35s	remaining: 7.71s
350:	learn: 0.0417644	total: 2.35s	remaining: 7.71s
351:	learn: 0.0417533	total: 2.36s	remaining: 7.7s
352:	learn: 0.0417403	total: 2.37s	remaining: 7.7s
353:	learn: 0.0417272	total: 2.38s	remaining: 7.7s
354:	learn: 0.0417192	total: 2.38s	remaining: 7.68s
355:	learn: 0.0417054	total: 2.39s	remaining: 7.68s
356:	learn: 0.0416887	total: 2.4s	remaining: 7.67s
357:	learn: 0.0416751	total: 2.4s	remaining: 7.67s
358:	learn: 0.0416595	total: 2.41s	remaining: 7.66s
359:	learn: 0.0416541	total: 2.41s	remaining: 7.64s
360:	learn: 0.0416372	total: 2.42s	remaining: 7.63s
361:	learn: 0.0416193	total: 2.43s	remaining: 7.63s
362:	learn: 0.0416086	total: 2.43s	remaining: 7.62s
363:	learn: 0.0415966	total: 2.44s	remaining: 7.62s
364:	learn: 0.0415819	total: 2.45s	remaining: 7.61s
365:	learn: 0.0415691	total: 2.46s	remaining: 7.61s
366:	learn: 0.0415566	total: 2.46s	remaining: 7.6s
367:	learn: 0.0415405	total: 2.47s	remaining: 7.6s
368:	learn: 0.0415272	total: 2.48s	remaining: 7.59s
369:	learn: 0.0415159	total: 2.48s	remaining: 7.59s
370:	learn: 0.0415019	total: 2.49s	remaining: 7.58s
371:	learn: 0.0414910	total: 2.5s	remaining: 7.58s
372:	learn: 0.0414790	total: 2.51s	remaining: 7.57s
373:	learn: 0.0414655	total: 2.51s	remaining: 7.57s
374:	learn: 0.0414491	total: 2.52s	remaining: 7.56s
375:	learn: 0.0414370	total: 2.53s	remaining: 7.55s
376:	learn: 0.0414268	total: 2.53s	remaining: 7.55s
377:	learn: 0.0414169	total: 2.54s	remaining: 7.54s
378:	learn: 0.0414075	total: 2.55s	remaining: 7.54s
379:	learn: 0.0413945	total: 2.56s	remaining: 7.53s
380:	learn: 0.0413816	total: 2.56s	remaining: 7.53s
381:	learn: 0.0413680	total: 2.57s	remaining: 7.52s
382:	learn: 0.0413522	total: 2.58s	remaining: 7.51s
383:	learn: 0.0413373	total: 2.58s	remaining: 7.51s
384:	learn: 0.0413269	total: 2.59s	remaining: 7.5s
385:	learn: 0.0413172	total: 2.6s	remaining: 7.49s
386:	learn: 0.0413077	total: 2.6s	remaining: 7.49s

0.9148246614651916

In [194]:
from sklearn.ensemble import RandomForestRegressor
model3=RandomForestRegressor(n_estimators=500,random_state=42,max_depth=20,min_samples_split=5,min_samples_leaf=3)
model3.fit(x_train,y_train)

y_pred3=model3.predict(x_test)
r2_score(y_test,y_pred3)

0.9213228280968373

In [192]:
from xgboost import XGBRegressor
model4=XGBRegressor(n_estimators=500,learning_rate=0.01,max_depth=10,subsample=0.8,colsample_bytree=0.8,random_state=42)
model4.fit(x_train,y_train) 

y_pred4=model4.predict(x_test)
r2_score(y_test,y_pred4)

0.9102344183226923

In [193]:
from lightgbm import LGBMRegressor
model5=LGBMRegressor(n_estimators=500,learning_rate=0.01,max_depth=10,subsample=0.8,colsample_bytree=0.8,random_state=42)
model5.fit(x_train,y_train)         
y_pred5=model5.predict(x_test)
r2_score(y_test,y_pred5)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000554 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 617
[LightGBM] [Info] Number of data points in the train set: 61839, number of used features: 6
[LightGBM] [Info] Start training from score 0.093784

0.911324275414234

In [195]:
from sklearn.ensemble import VotingRegressor
voting_model=VotingRegressor(estimators=[('catboost',model2),('random_forest',model3)],weights=[0.35,0.65])
voting_model.fit(x_train,y_train)
y_pred_voting=voting_model.predict(x_test)
r2_score(y_test,y_pred_voting)

0:	learn: 0.1409433	total: 16.9ms	remaining: 25.3s
1:	learn: 0.1397710	total: 40.3ms	remaining: 30.2s
2:	learn: 0.1385669	total: 48.2ms	remaining: 24s
3:	learn: 0.1373935	total: 51.1ms	remaining: 19.1s
4:	learn: 0.1362125	total: 57.7ms	remaining: 17.3s
5:	learn: 0.1350757	total: 62.4ms	remaining: 15.5s
6:	learn: 0.1339617	total: 71.5ms	remaining: 15.3s
7:	learn: 0.1328084	total: 78.1ms	remaining: 14.6s
8:	learn: 0.1316994	total: 90.5ms	remaining: 15s
9:	learn: 0.1306049	total: 97ms	remaining: 14.5s
10:	learn: 0.1295121	total: 103ms	remaining: 14s
11:	learn: 0.1284217	total: 110ms	remaining: 13.6s
12:	learn: 0.1273537	total: 113ms	remaining: 13s
13:	learn: 0.1262701	total: 120ms	remaining: 12.8s
14:	learn: 0.1252408	total: 124ms	remaining: 12.2s
15:	learn: 0.1242148	total: 128ms	remaining: 11.9s
16:	learn: 0.1231858	total: 131ms	remaining: 11.5s
17:	learn: 0.1221869	total: 138ms	remaining: 11.3s
18:	learn: 0.1211978	total: 140ms	remaining: 10.9s
19:	learn: 0.1202087	total: 148ms	remaining: 11s
20:	learn: 0.1192517	total: 152ms	remaining: 10.7s
21:	learn: 0.1182742	total: 158ms	remaining: 10.6s
22:	learn: 0.1173158	total: 166ms	remaining: 10.6s
23:	learn: 0.1163560	total: 172ms	remaining: 10.6s
24:	learn: 0.1154005	total: 178ms	remaining: 10.5s
25:	learn: 0.1144561	total: 184ms	remaining: 10.4s
26:	learn: 0.1135620	total: 187ms	remaining: 10.2s
27:	learn: 0.1126470	total: 193ms	remaining: 10.2s
28:	learn: 0.1117429	total: 199ms	remaining: 10.1s
29:	learn: 0.1108443	total: 204ms	remaining: 9.98s
30:	learn: 0.1099909	total: 206ms	remaining: 9.76s
31:	learn: 0.1091425	total: 209ms	remaining: 9.6s
32:	learn: 0.1082703	total: 216ms	remaining: 9.59s
33:	learn: 0.1074122	total: 222ms	remaining: 9.57s
34:	learn: 0.1065669	total: 228ms	remaining: 9.55s
35:	learn: 0.1057362	total: 235ms	remaining: 9.54s
36:	learn: 0.1048983	total: 241ms	remaining: 9.54s
37:	learn: 0.1041167	total: 243ms	remaining: 9.36s
38:	learn: 0.1032982	total: 249ms	remaining: 9.35s
39:	learn: 0.1025148	total: 256ms	remaining: 9.35s
40:	learn: 0.1017203	total: 262ms	remaining: 9.33s
41:	learn: 0.1009624	total: 265ms	remaining: 9.21s
42:	learn: 0.1002040	total: 271ms	remaining: 9.19s
43:	learn: 0.0994233	total: 277ms	remaining: 9.18s
44:	learn: 0.0986835	total: 283ms	remaining: 9.16s
45:	learn: 0.0979271	total: 290ms	remaining: 9.16s
46:	learn: 0.0972003	total: 294ms	remaining: 9.1s
47:	learn: 0.0964753	total: 301ms	remaining: 9.1s
48:	learn: 0.0957593	total: 307ms	remaining: 9.09s
49:	learn: 0.0950649	total: 313ms	remaining: 9.08s
50:	learn: 0.0943553	total: 320ms	remaining: 9.08s
51:	learn: 0.0936529	total: 326ms	remaining: 9.06s
52:	learn: 0.0929792	total: 332ms	remaining: 9.06s
53:	learn: 0.0922942	total: 338ms	remaining: 9.05s
54:	learn: 0.0916404	total: 344ms	remaining: 9.03s
55:	learn: 0.0909789	total: 350ms	remaining: 9.02s
56:	learn: 0.0903234	total: 357ms	remaining: 9.03s
57:	learn: 0.0896740	total: 363ms	remaining: 9.04s
58:	learn: 0.0890696	total: 371ms	remaining: 9.05s
59:	learn: 0.0884263	total: 378ms	remaining: 9.07s
60:	learn: 0.0878078	total: 386ms	remaining: 9.1s
61:	learn: 0.0871810	total: 395ms	remaining: 9.15s
62:	learn: 0.0865580	total: 403ms	remaining: 9.19s
63:	learn: 0.0859504	total: 412ms	remaining: 9.23s
64:	learn: 0.0853517	total: 426ms	remaining: 9.4s
65:	learn: 0.0847522	total: 442ms	remaining: 9.6s
66:	learn: 0.0841674	total: 454ms	remaining: 9.71s
67:	learn: 0.0835949	total: 466ms	remaining: 9.81s
68:	learn: 0.0830323	total: 479ms	remaining: 9.93s
69:	learn: 0.0824624	total: 492ms	remaining: 10s
70:	learn: 0.0819001	total: 502ms	remaining: 10.1s
71:	learn: 0.0813540	total: 511ms	remaining: 10.1s
72:	learn: 0.0808241	total: 519ms	remaining: 10.1s
73:	learn: 0.0802796	total: 527ms	remaining: 10.2s
74:	learn: 0.0797505	total: 536ms	remaining: 10.2s
75:	learn: 0.0792312	total: 545ms	remaining: 10.2s
76:	learn: 0.0787196	total: 553ms	remaining: 10.2s
77:	learn: 0.0782179	total: 562ms	remaining: 10.2s
78:	learn: 0.0777066	total: 570ms	remaining: 10.3s
79:	learn: 0.0772127	total: 579ms	remaining: 10.3s
80:	learn: 0.0767085	total: 587ms	remaining: 10.3s
81:	learn: 0.0762221	total: 594ms	remaining: 10.3s
82:	learn: 0.0757485	total: 599ms	remaining: 10.2s
83:	learn: 0.0752707	total: 606ms	remaining: 10.2s
84:	learn: 0.0748043	total: 614ms	remaining: 10.2s
85:	learn: 0.0743383	total: 621ms	remaining: 10.2s
86:	learn: 0.0738769	total: 629ms	remaining: 10.2s
87:	learn: 0.0734325	total: 636ms	remaining: 10.2s
88:	learn: 0.0729932	total: 644ms	remaining: 10.2s
89:	learn: 0.0725609	total: 649ms	remaining: 10.2s
90:	learn: 0.0721370	total: 653ms	remaining: 10.1s
91:	learn: 0.0717022	total: 660ms	remaining: 10.1s
92:	learn: 0.0712779	total: 665ms	remaining: 10.1s
93:	learn: 0.0708587	total: 672ms	remaining: 10.1s
94:	learn: 0.0704483	total: 679ms	remaining: 10s
95:	learn: 0.0700616	total: 683ms	remaining: 9.99s
96:	learn: 0.0696578	total: 690ms	remaining: 9.98s
97:	learn: 0.0692611	total: 697ms	remaining: 9.98s
98:	learn: 0.0688678	total: 705ms	remaining: 9.97s
99:	learn: 0.0684826	total: 712ms	remaining: 9.97s
100:	learn: 0.0681019	total: 719ms	remaining: 9.95s
101:	learn: 0.0677185	total: 725ms	remaining: 9.93s
102:	learn: 0.0673326	total: 731ms	remaining: 9.92s
103:	learn: 0.0669844	total: 735ms	remaining: 9.86s
104:	learn: 0.0666153	total: 742ms	remaining: 9.86s
105:	learn: 0.0662672	total: 747ms	remaining: 9.83s
106:	learn: 0.0659158	total: 754ms	remaining: 9.82s
107:	learn: 0.0655542	total: 761ms	remaining: 9.81s
108:	learn: 0.0652159	total: 768ms	remaining: 9.8s
109:	learn: 0.0648751	total: 775ms	remaining: 9.79s
110:	learn: 0.0645312	total: 782ms	remaining: 9.79s
111:	learn: 0.0642162	total: 789ms	remaining: 9.78s
112:	learn: 0.0638866	total: 796ms	remaining: 9.77s
113:	learn: 0.0635714	total: 803ms	remaining: 9.76s
114:	learn: 0.0632619	total: 806ms	remaining: 9.71s
115:	learn: 0.0629472	total: 814ms	remaining: 9.71s
116:	learn: 0.0626462	total: 821ms	remaining: 9.7s
117:	learn: 0.0623399	total: 828ms	remaining: 9.69s
118:	learn: 0.0620434	total: 835ms	remaining: 9.69s
119:	learn: 0.0617434	total: 843ms	remaining: 9.7s
120:	learn: 0.0614597	total: 851ms	remaining: 9.7s
121:	learn: 0.0611642	total: 858ms	remaining: 9.69s
122:	learn: 0.0608659	total: 865ms	remaining: 9.68s
123:	learn: 0.0605806	total: 872ms	remaining: 9.68s
124:	learn: 0.0603212	total: 875ms	remaining: 9.63s
125:	learn: 0.0600484	total: 883ms	remaining: 9.62s
126:	learn: 0.0597818	total: 890ms	remaining: 9.63s
127:	learn: 0.0595141	total: 899ms	remaining: 9.63s
128:	learn: 0.0592413	total: 906ms	remaining: 9.63s
129:	learn: 0.0589775	total: 913ms	remaining: 9.63s
130:	learn: 0.0587110	total: 920ms	remaining: 9.62s
131:	learn: 0.0584584	total: 928ms	remaining: 9.61s
132:	learn: 0.0582086	total: 935ms	remaining: 9.61s
133:	learn: 0.0579552	total: 942ms	remaining: 9.61s
134:	learn: 0.0577123	total: 950ms	remaining: 9.6s
135:	learn: 0.0574732	total: 958ms	remaining: 9.6s
136:	learn: 0.0572352	total: 965ms	remaining: 9.6s
137:	learn: 0.0570127	total: 973ms	remaining: 9.6s
138:	learn: 0.0567822	total: 981ms	remaining: 9.61s
139:	learn: 0.0565665	total: 986ms	remaining: 9.58s
140:	learn: 0.0563425	total: 994ms	remaining: 9.58s
141:	learn: 0.0561269	total: 1s	remaining: 9.57s
142:	learn: 0.0559105	total: 1.01s	remaining: 9.57s
143:	learn: 0.0557007	total: 1.02s	remaining: 9.58s
144:	learn: 0.0554922	total: 1.02s	remaining: 9.59s
145:	learn: 0.0552921	total: 1.03s	remaining: 9.58s
146:	learn: 0.0550852	total: 1.04s	remaining: 9.59s
147:	learn: 0.0548778	total: 1.05s	remaining: 9.59s
148:	learn: 0.0546721	total: 1.06s	remaining: 9.59s
149:	learn: 0.0544779	total: 1.07s	remaining: 9.6s
150:	learn: 0.0542819	total: 1.07s	remaining: 9.6s
151:	learn: 0.0540930	total: 1.08s	remaining: 9.6s
152:	learn: 0.0539054	total: 1.09s	remaining: 9.61s
153:	learn: 0.0537110	total: 1.1s	remaining: 9.6s
154:	learn: 0.0535251	total: 1.1s	remaining: 9.6s
155:	learn: 0.0533485	total: 1.11s	remaining: 9.59s
156:	learn: 0.0531747	total: 1.12s	remaining: 9.58s
157:	learn: 0.0529995	total: 1.13s	remaining: 9.57s
158:	learn: 0.0528182	total: 1.13s	remaining: 9.57s
159:	learn: 0.0526534	total: 1.14s	remaining: 9.56s
160:	learn: 0.0524845	total: 1.15s	remaining: 9.55s
161:	learn: 0.0523175	total: 1.16s	remaining: 9.54s
162:	learn: 0.0521572	total: 1.16s	remaining: 9.53s
163:	learn: 0.0519916	total: 1.17s	remaining: 9.52s
164:	learn: 0.0518436	total: 1.17s	remaining: 9.49s
165:	learn: 0.0516840	total: 1.18s	remaining: 9.49s
166:	learn: 0.0515372	total: 1.19s	remaining: 9.48s
167:	learn: 0.0513862	total: 1.19s	remaining: 9.47s
168:	learn: 0.0512402	total: 1.2s	remaining: 9.47s
169:	learn: 0.0510988	total: 1.21s	remaining: 9.46s
170:	learn: 0.0509589	total: 1.22s	remaining: 9.45s
171:	learn: 0.0508232	total: 1.22s	remaining: 9.44s
172:	learn: 0.0506824	total: 1.23s	remaining: 9.44s
173:	learn: 0.0505469	total: 1.24s	remaining: 9.43s
174:	learn: 0.0504179	total: 1.24s	remaining: 9.42s
175:	learn: 0.0502846	total: 1.25s	remaining: 9.41s
176:	learn: 0.0501485	total: 1.26s	remaining: 9.41s
177:	learn: 0.0500174	total: 1.26s	remaining: 9.4s
178:	learn: 0.0498844	total: 1.27s	remaining: 9.39s
179:	learn: 0.0497573	total: 1.28s	remaining: 9.39s
180:	learn: 0.0496342	total: 1.29s	remaining: 9.38s
181:	learn: 0.0495076	total: 1.29s	remaining: 9.37s
182:	learn: 0.0493872	total: 1.3s	remaining: 9.37s
183:	learn: 0.0492667	total: 1.31s	remaining: 9.36s
184:	learn: 0.0491540	total: 1.31s	remaining: 9.35s
185:	learn: 0.0490307	total: 1.32s	remaining: 9.34s
186:	learn: 0.0489145	total: 1.33s	remaining: 9.34s
187:	learn: 0.0487996	total: 1.34s	remaining: 9.33s
188:	learn: 0.0486882	total: 1.34s	remaining: 9.32s
189:	learn: 0.0485812	total: 1.35s	remaining: 9.32s
190:	learn: 0.0484717	total: 1.36s	remaining: 9.32s
191:	learn: 0.0483640	total: 1.37s	remaining: 9.31s
192:	learn: 0.0482667	total: 1.37s	remaining: 9.3s
193:	learn: 0.0481658	total: 1.38s	remaining: 9.3s
194:	learn: 0.0480665	total: 1.39s	remaining: 9.3s
195:	learn: 0.0479672	total: 1.4s	remaining: 9.29s
196:	learn: 0.0478685	total: 1.4s	remaining: 9.28s
197:	learn: 0.0477678	total: 1.41s	remaining: 9.28s
198:	learn: 0.0476829	total: 1.42s	remaining: 9.25s
199:	learn: 0.0475870	total: 1.42s	remaining: 9.24s
200:	learn: 0.0475019	total: 1.43s	remaining: 9.24s
201:	learn: 0.0474135	total: 1.44s	remaining: 9.23s
202:	learn: 0.0473200	total: 1.44s	remaining: 9.23s
203:	learn: 0.0472327	total: 1.45s	remaining: 9.22s
204:	learn: 0.0471496	total: 1.46s	remaining: 9.22s
205:	learn: 0.0470571	total: 1.47s	remaining: 9.21s
206:	learn: 0.0469867	total: 1.47s	remaining: 9.2s
207:	learn: 0.0469095	total: 1.48s	remaining: 9.19s
208:	learn: 0.0468421	total: 1.48s	remaining: 9.16s
209:	learn: 0.0467534	total: 1.49s	remaining: 9.16s
210:	learn: 0.0466758	total: 1.5s	remaining: 9.16s
211:	learn: 0.0465953	total: 1.51s	remaining: 9.15s
212:	learn: 0.0465301	total: 1.51s	remaining: 9.13s
213:	learn: 0.0464590	total: 1.52s	remaining: 9.12s
214:	learn: 0.0463854	total: 1.52s	remaining: 9.11s
215:	learn: 0.0463123	total: 1.53s	remaining: 9.11s
216:	learn: 0.0462416	total: 1.54s	remaining: 9.1s
217:	learn: 0.0461596	total: 1.55s	remaining: 9.1s
218:	learn: 0.0460918	total: 1.55s	remaining: 9.09s
219:	learn: 0.0460186	total: 1.56s	remaining: 9.08s
220:	learn: 0.0459527	total: 1.57s	remaining: 9.07s
221:	learn: 0.0458848	total: 1.57s	remaining: 9.07s
222:	learn: 0.0458320	total: 1.58s	remaining: 9.04s
223:	learn: 0.0457601	total: 1.59s	remaining: 9.04s
224:	learn: 0.0456894	total: 1.59s	remaining: 9.03s
225:	learn: 0.0456242	total: 1.6s	remaining: 9.02s
226:	learn: 0.0455592	total: 1.61s	remaining: 9.02s
227:	learn: 0.0454966	total: 1.61s	remaining: 9.01s
228:	learn: 0.0454336	total: 1.62s	remaining: 9s
229:	learn: 0.0453726	total: 1.63s	remaining: 9s
230:	learn: 0.0453154	total: 1.64s	remaining: 8.99s
231:	learn: 0.0452546	total: 1.64s	remaining: 8.99s
232:	learn: 0.0451989	total: 1.65s	remaining: 8.98s
233:	learn: 0.0451356	total: 1.66s	remaining: 8.98s
234:	learn: 0.0450869	total: 1.67s	remaining: 8.97s
235:	learn: 0.0450301	total: 1.67s	remaining: 8.96s
236:	learn: 0.0449759	total: 1.68s	remaining: 8.96s
237:	learn: 0.0449255	total: 1.69s	remaining: 8.95s
238:	learn: 0.0448745	total: 1.7s	remaining: 8.95s
239:	learn: 0.0448258	total: 1.7s	remaining: 8.94s
240:	learn: 0.0447765	total: 1.71s	remaining: 8.94s
241:	learn: 0.0447301	total: 1.72s	remaining: 8.93s
242:	learn: 0.0446805	total: 1.73s	remaining: 8.93s
243:	learn: 0.0446315	total: 1.73s	remaining: 8.93s
244:	learn: 0.0445852	total: 1.74s	remaining: 8.93s
245:	learn: 0.0445400	total: 1.75s	remaining: 8.93s
246:	learn: 0.0444999	total: 1.76s	remaining: 8.93s
247:	learn: 0.0444549	total: 1.77s	remaining: 8.93s
248:	learn: 0.0444014	total: 1.78s	remaining: 8.93s
249:	learn: 0.0443510	total: 1.78s	remaining: 8.93s
250:	learn: 0.0443056	total: 1.79s	remaining: 8.93s
251:	learn: 0.0442518	total: 1.8s	remaining: 8.93s
252:	learn: 0.0442072	total: 1.81s	remaining: 8.93s
253:	learn: 0.0441586	total: 1.82s	remaining: 8.93s
254:	learn: 0.0441162	total: 1.83s	remaining: 8.92s
255:	learn: 0.0440714	total: 1.84s	remaining: 8.93s
256:	learn: 0.0440333	total: 1.85s	remaining: 8.93s
257:	learn: 0.0439923	total: 1.85s	remaining: 8.93s
258:	learn: 0.0439483	total: 1.86s	remaining: 8.93s
259:	learn: 0.0439059	total: 1.87s	remaining: 8.94s
260:	learn: 0.0438659	total: 1.88s	remaining: 8.93s
261:	learn: 0.0438264	total: 1.89s	remaining: 8.93s
262:	learn: 0.0438011	total: 1.89s	remaining: 8.91s
263:	learn: 0.0437601	total: 1.9s	remaining: 8.91s
264:	learn: 0.0437221	total: 1.91s	remaining: 8.91s
265:	learn: 0.0436882	total: 1.92s	remaining: 8.91s
266:	learn: 0.0436481	total: 1.93s	remaining: 8.91s
267:	learn: 0.0436060	total: 1.94s	remaining: 8.91s
268:	learn: 0.0435718	total: 1.95s	remaining: 8.91s
269:	learn: 0.0435361	total: 1.96s	remaining: 8.91s
270:	learn: 0.0435028	total: 1.97s	remaining: 8.92s
271:	learn: 0.0434685	total: 1.98s	remaining: 8.93s
272:	learn: 0.0434333	total: 1.99s	remaining: 8.93s
273:	learn: 0.0433929	total: 2s	remaining: 8.94s
274:	learn: 0.0433620	total: 2.01s	remaining: 8.94s
275:	learn: 0.0433392	total: 2.01s	remaining: 8.92s
276:	learn: 0.0433048	total: 2.02s	remaining: 8.92s
277:	learn: 0.0432671	total: 2.03s	remaining: 8.92s
278:	learn: 0.0432358	total: 2.04s	remaining: 8.92s
279:	learn: 0.0432162	total: 2.04s	remaining: 8.89s
280:	learn: 0.0431902	total: 2.05s	remaining: 8.9s
281:	learn: 0.0431685	total: 2.06s	remaining: 8.89s
282:	learn: 0.0431371	total: 2.07s	remaining: 8.89s
283:	learn: 0.0431102	total: 2.08s	remaining: 8.9s
284:	learn: 0.0430779	total: 2.09s	remaining: 8.91s
285:	learn: 0.0430542	total: 2.1s	remaining: 8.91s
286:	learn: 0.0430241	total: 2.11s	remaining: 8.91s
287:	learn: 0.0429936	total: 2.12s	remaining: 8.91s
288:	learn: 0.0429703	total: 2.13s	remaining: 8.91s
289:	learn: 0.0429468	total: 2.13s	remaining: 8.91s
290:	learn: 0.0429158	total: 2.15s	remaining: 8.91s
291:	learn: 0.0428830	total: 2.15s	remaining: 8.91s
292:	learn: 0.0428554	total: 2.16s	remaining: 8.91s
293:	learn: 0.0428320	total: 2.17s	remaining: 8.91s
294:	learn: 0.0428054	total: 2.18s	remaining: 8.91s
295:	learn: 0.0427819	total: 2.19s	remaining: 8.9s
296:	learn: 0.0427589	total: 2.2s	remaining: 8.9s
297:	learn: 0.0427357	total: 2.21s	remaining: 8.9s
298:	learn: 0.0427055	total: 2.21s	remaining: 8.9s
299:	learn: 0.0426813	total: 2.22s	remaining: 8.9s
300:	learn: 0.0426578	total: 2.23s	remaining: 8.9s
301:	learn: 0.0426384	total: 2.25s	remaining: 8.91s
302:	learn: 0.0426137	total: 2.26s	remaining: 8.92s
303:	learn: 0.0425929	total: 2.27s	remaining: 8.93s
304:	learn: 0.0425799	total: 2.27s	remaining: 8.91s
305:	learn: 0.0425535	total: 2.29s	remaining: 8.93s
306:	learn: 0.0425288	total: 2.3s	remaining: 8.94s
307:	learn: 0.0425075	total: 2.31s	remaining: 8.94s
308:	learn: 0.0424846	total: 2.32s	remaining: 8.94s
309:	learn: 0.0424666	total: 2.33s	remaining: 8.95s
310:	learn: 0.0424471	total: 2.34s	remaining: 8.95s
311:	learn: 0.0424270	total: 2.35s	remaining: 8.95s
312:	learn: 0.0424020	total: 2.36s	remaining: 8.95s
313:	learn: 0.0423824	total: 2.37s	remaining: 8.95s
314:	learn: 0.0423618	total: 2.38s	remaining: 8.95s
315:	learn: 0.0423391	total: 2.39s	remaining: 8.94s
316:	learn: 0.0423155	total: 2.4s	remaining: 8.94s
317:	learn: 0.0422981	total: 2.4s	remaining: 8.94s
318:	learn: 0.0422776	total: 2.42s	remaining: 8.94s
319:	learn: 0.0422583	total: 2.42s	remaining: 8.94s
320:	learn: 0.0422352	total: 2.44s	remaining: 8.94s
321:	learn: 0.0422123	total: 2.44s	remaining: 8.94s
322:	learn: 0.0421961	total: 2.46s	remaining: 8.95s
323:	learn: 0.0421806	total: 2.46s	remaining: 8.95s
324:	learn: 0.0421608	total: 2.48s	remaining: 8.95s
325:	learn: 0.0421416	total: 2.48s	remaining: 8.95s
326:	learn: 0.0421239	total: 2.5s	remaining: 8.95s
327:	learn: 0.0421093	total: 2.5s	remaining: 8.95s
328:	learn: 0.0420903	total: 2.51s	remaining: 8.95s
329:	learn: 0.0420744	total: 2.52s	remaining: 8.94s
330:	learn: 0.0420591	total: 2.53s	remaining: 8.94s
331:	learn: 0.0420442	total: 2.54s	remaining: 8.94s
332:	learn: 0.0420274	total: 2.55s	remaining: 8.94s
333:	learn: 0.0420134	total: 2.56s	remaining: 8.93s
334:	learn: 0.0420009	total: 2.57s	remaining: 8.93s
335:	learn: 0.0419813	total: 2.58s	remaining: 8.93s
336:	learn: 0.0419661	total: 2.58s	remaining: 8.92s
337:	learn: 0.0419503	total: 2.59s	remaining: 8.92s
338:	learn: 0.0419362	total: 2.6s	remaining: 8.91s
339:	learn: 0.0419201	total: 2.61s	remaining: 8.91s
340:	learn: 0.0419041	total: 2.62s	remaining: 8.91s
341:	learn: 0.0418847	total: 2.63s	remaining: 8.9s
342:	learn: 0.0418711	total: 2.64s	remaining: 8.9s
343:	learn: 0.0418575	total: 2.65s	remaining: 8.9s
344:	learn: 0.0418503	total: 2.65s	remaining: 8.88s
345:	learn: 0.0418327	total: 2.66s	remaining: 8.88s
346:	learn: 0.0418197	total: 2.67s	remaining: 8.88s
347:	learn: 0.0418034	total: 2.68s	remaining: 8.88s
348:	learn: 0.0417910	total: 2.69s	remaining: 8.87s
349:	learn: 0.0417788	total: 2.7s	remaining: 8.87s
350:	learn: 0.0417644	total: 2.71s	remaining: 8.87s
351:	learn: 0.0417533	total: 2.72s	remaining: 8.88s
352:	learn: 0.0417403	total: 2.79s	remaining: 9.07s
353:	learn: 0.0417272	total: 2.81s	remaining: 9.1s
354:	learn: 0.0417192	total: 2.81s	remaining: 9.08s
355:	learn: 0.0417054	total: 2.83s	remaining: 9.09s
356:	learn: 0.0416887	total: 2.84s	remaining: 9.1s
357:	learn: 0.0416751	total: 2.85s	remaining: 9.09s
358:	learn: 0.0416595	total: 2.86s	remaining: 9.08s
359:	learn: 0.0416541	total: 2.86s	remaining: 9.06s
360:	learn: 0.0416372	total: 2.87s	remaining: 9.05s
361:	learn: 0.0416193	total: 2.88s	remaining: 9.05s
362:	learn: 0.0416086	total: 2.89s	remaining: 9.04s
363:	learn: 0.0415966	total: 2.9s	remaining: 9.04s
364:	learn: 0.0415819	total: 2.9s	remaining: 9.03s
365:	learn: 0.0415691	total: 2.91s	remaining: 9.03s
366:	learn: 0.0415566	total: 2.92s	remaining: 9.02s
367:	learn: 0.0415405	total: 2.93s	remaining: 9.02s
368:	learn: 0.0415272	total: 2.94s	remaining: 9.02s
369:	learn: 0.0415159	total: 2.95s	remaining: 9.01s
370:	learn: 0.0415019	total: 2.96s	remaining: 9s
371:	learn: 0.0414910	total: 2.97s	remaining: 9s
372:	learn: 0.0414790	total: 2.98s	remaining: 8.99s
373:	learn: 0.0414655	total: 2.98s	remaining: 8.99s
374:	learn: 0.0414491	total: 2.99s	remaining: 8.98s
375:	learn: 0.0414370	total: 3s	remaining: 8.97s
376:	learn: 0.0414268	total: 3.01s	remaining: 8.97s
377:	learn: 0.0414169	total: 3.02s	remaining: 8.97s
378:	learn: 0.0414075	total: 3.03s	remaining: 8.96s
379:	learn: 0.0413945	total: 3.04s	remaining: 8.96s
380:	learn: 0.0413816	total: 3.05s	remaining: 8.96s
381:	learn: 0.0413680	total: 3.06s	remaining: 8.95s
382:	learn: 0.0413522	total: 3.07s	remaining: 8.94s
383:	learn: 0.0413373	total: 3.07s	remaining: 8.94s
384:	learn: 0.0413269	total: 3.08s	remaining: 8.93s
385:	learn: 0.0413172	total: 3.09s	remaining: 8.93s
386:	learn: 0.0413077	total: 3.1s	remaining: 8.92s
387:	learn: 0.0412971	total: 3.11s	remaining: 8.92s

0.9217105890376335